import { type FormEvent, useRef, useState } from "react";
import { browserApi, type AdminApi, type AdminSession } from "./api";
import { AccessManagement } from "./access-management";
import { ContentOperations } from "./content-operations";
import { CustomerManagement } from "./customer-management";
import { ModelOperations } from "./model-operations";
import { PricingOperations } from "./pricing-operations";
import { AccountSecurity } from "./account-security";
export type { AdminApi, AdminSession } from "./api";

type View = "Overview" | "Customers" | "Models" | "Pricing" | "Content" | "Access" | "Security";
const labels: Record<View, string> = { Overview: "概览", Customers: "客户管理", Models: "模型配置", Pricing: "模型计费", Content: "内容运营", Access: "权限管理", Security: "账号安全" };
const allowed = (p: string[]): View[] => { const views: View[] = ["Overview", "Security"]; if (p.some(x => ["customer_accounts.read", "customer_accounts.create", "customer_accounts.reset_password", "customer_accounts.disable", "model_assignments.manage"].includes(x))) views.push("Customers"); if (p.some(x => ["model_configs.read", "model_configs.manage"].includes(x))) views.push("Models"); if (p.some(x => ["model_pricing.read", "model_pricing.manage", "model_usage.read"].includes(x))) views.push("Pricing"); if (p.some(x => ["content_templates.read", "content_templates.edit", "content_templates.publish", "review_rules.read", "review_rules.edit", "review_rules.publish"].includes(x))) views.push("Content"); if (p.some(x => ["roles.manage", "internal_accounts.read", "internal_accounts.manage", "audit.read"].includes(x))) views.push("Access"); return views; };

export function App({ session, api }: { session?: AdminSession; api?: AdminApi }) { const clientRef = useRef<AdminApi | null>(null); if (!clientRef.current) clientRef.current = browserApi(); const client = api ?? clientRef.current; const [current, setCurrent] = useState(session); return current ? <Console session={current} api={client} onPasswordChanged={() => setCurrent(undefined)} /> : <Login api={client} onLogin={setCurrent} />; }
function Login({ api, onLogin }: { api: AdminApi; onLogin: (session: AdminSession) => void }) { const [failure, setFailure] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { setFailure(false); onLogin(await api.login(String(form.get("loginName") ?? ""), String(form.get("password") ?? ""))); } catch { setFailure(true); } finally { formElement.reset(); } } return <main className="login"><form onSubmit={event => void submit(event)}><h1>餐饮运营管理后台</h1><label>账号<input name="loginName" required /></label><label>密码<input name="password" type="password" required /></label>{failure && <p role="alert">账号、密码或后台权限无效</p>}<button>登录</button></form></main>; }
function Console({ session, api, onPasswordChanged }: { session: AdminSession; api: AdminApi; onPasswordChanged: () => void }) { const views = allowed(session.permissions); const [view, setView] = useState<View>(views[0]!); return <div className="shell"><aside><strong>餐饮运营</strong><small>{session.account.displayName}</small><nav aria-label="管理导航">{views.map(item => <button className={view === item ? "selected" : ""} key={item} onClick={() => setView(item)}>{labels[item]}</button>)}</nav></aside><main><h1>{labels[view]}</h1>{view === "Overview" && <p>仅展示安全运行状态与汇总信息，不展示客户原始内容、素材、审核记录或对象地址。</p>}{view === "Security" && <AccountSecurity api={api} onPasswordChanged={onPasswordChanged} />}{view === "Customers" && <CustomerManagement api={api} permissions={session.permissions} />}{view === "Models" && <ModelOperations api={api} permissions={session.permissions} />}{view === "Pricing" && <PricingOperations api={api} permissions={session.permissions} />}{view === "Content" && <ContentOperations api={api} permissions={session.permissions} />}{view === "Access" && <AccessManagement api={api} permissions={session.permissions} />}</main></div>; }
