import { type FormEvent, useEffect, useState } from "react";

export type AdminSession = { account: { id: string; displayName: string }; permissions: string[] };
export type AdminApi = { request(path: string, init?: RequestInit): Promise<Response>; login?(loginName:string,password:string):Promise<AdminSession> };
type View = "概览" | "客户管理" | "内容运营" | "模型运营" | "权限管理";

export function App({ session, api = browserApi() }: { session?: AdminSession; api?: AdminApi }) {
  const [current,setCurrent]=useState(session);
  if(!current)return <Login api={api} onLogin={setCurrent}/>;
  return <Console session={current} api={api}/>;
}
function Login({api,onLogin}:{api:AdminApi;onLogin:(s:AdminSession)=>void}){const [name,setName]=useState("");const [password,setPassword]=useState("");const [bad,setBad]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();try{if(!api.login)throw new Error();onLogin(await api.login(name,password));}catch{setBad(true)}finally{setPassword("")}}return <main><form onSubmit={(e)=>void submit(e)}><h1>餐饮运营管理后台</h1><label>账号<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{bad&&<p role="alert">账号、密码或后台权限无效。</p>}<button>登录</button></form></main>}
function Console({ session, api }: { session: AdminSession; api?: AdminApi }) {
  const views = allowedViews(session.permissions); const [view, setView] = useState<View>(views[0]!);
  return <div className="shell"><aside><strong>餐饮运营</strong><small>{session.account.displayName}</small><nav aria-label="管理导航">{views.map((item) => <button className={view === item ? "selected" : ""} key={item} onClick={() => setView(item)}>{item}</button>)}</nav></aside><main><h1>{view}</h1>{view === "概览" && <p>仅展示安全运行状态和汇总信息，不展示客户原始内容、素材、审核记录或对象地址。</p>}{view === "客户管理" && <Customers permissions={session.permissions} api={api} />}{view === "内容运营" && <p>模板与审核规则只允许版本化发布；不展示客户文案或审核记录。</p>}{view === "模型运营" && <Models permissions={session.permissions} api={api} />}{view === "权限管理" && <><p>服务端权限摘要</p><ul>{session.permissions.map((permission) => <li key={permission}>{permission}</li>)}</ul></>}</main></div>;
}
function browserApi():AdminApi{let token="";const request=(path:string,init:RequestInit={})=>fetch(path,{...init,headers:{...init.headers,Authorization:`Bearer ${token}`}});return{request,async login(loginName,password){const login=await fetch("/v1/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({loginName,password})});if(!login.ok)throw new Error();const value=await login.json() as {accessToken:string};token=value.accessToken;const summary=await request("/v1/auth/me/internal-permissions");if(!summary.ok)throw new Error();return summary.json() as Promise<AdminSession>;}}}

function Customers({ permissions, api }: { permissions: string[]; api?: AdminApi }) {
  const [items, setItems] = useState<Array<{id:string;loginName:string;displayName:string;enterpriseId:string;storeId:string;enabled:boolean;passwordChangeRequired:boolean}>>([]);
  useEffect(() => { if (!api || !permissions.includes("customer_accounts.read")) return; void api.request("/v1/admin/customer-accounts?limit=50").then(async (response) => { if (!response.ok) return; const value = await response.json() as {items?: typeof items}; setItems(value.items ?? []); }); }, [api, permissions]);
  return <section><h2>客户账号</h2><p>仅列出客户账号、登录手机号、状态和所属企业/门店，不含任何客户原始内容。</p>{permissions.includes("customer_accounts.create") && <CustomerCreate api={api} />}{permissions.includes("customer_accounts.read") && <ul>{items.map((item) => <li key={item.id}>{item.displayName} · {item.loginName} · {item.enterpriseId}/{item.storeId} · {item.enabled ? "启用" : "停用"}{item.passwordChangeRequired ? " · 待修改初始密码" : ""}</li>)}</ul>}</section>;
}

function CustomerCreate({ api }: { api?: AdminApi }) { const [message, setMessage] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!api) return; const response = await api.request("/v1/admin/customer-accounts", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))}); const value = await response.json().catch(() => ({})) as {temporaryPassword?:string}; setMessage(response.ok && value.temporaryPassword ? `临时密码（仅显示一次）：${value.temporaryPassword}` : "创建未完成，请检查输入和权限。"); } return <form onSubmit={(event) => void submit(event)}><h3>新建客户</h3><Field name="mobile" label="手机号" /><Field name="displayName" label="名称" /><Field name="enterpriseId" label="企业 ID" /><Field name="storeId" label="门店 ID" /><label>门店角色<select name="storeRole"><option value="owner">负责人</option><option value="operator">运营人员</option></select></label><button>创建</button>{message && <p role="status">{message}</p>}</form>; }

function Models({ permissions, api }: { permissions: string[]; api?: AdminApi }) { const [items, setItems] = useState<Array<{id:string;label:string;provider:string;model:string;enabled:boolean;isDefault:boolean;keySuffix:string}>>([]); useEffect(() => { if (!api || !permissions.includes("model_configs.read")) return; void api.request("/v1/admin/model-configs").then(async (response) => { if (response.ok) setItems(((await response.json()) as {items?: typeof items}).items ?? []); }); }, [api, permissions]); return <section><h2>模型配置</h2><p>密钥只在提交时传给服务端加密保存；管理端不读取、不展示明文或密文。</p><ul>{items.map((item) => <li key={item.id}>{item.label} · {item.provider}/{item.model} · {item.enabled ? "启用" : "停用"}{item.isDefault ? " · 默认" : ""}{item.keySuffix ? ` · 密钥末尾 ${item.keySuffix}` : ""}</li>)}</ul></section>; }
function Field({name,label}:{name:string;label:string}) { return <label>{label}<input name={name} required /></label>; }
function allowedViews(permissions: string[]): View[] { const result: View[]=["概览"]; if (permissions.some((value)=>value.startsWith("customer_accounts")||value==="model_assignments.manage")) result.push("客户管理"); if (permissions.some((value)=>value.startsWith("content_templates")||value.startsWith("review_rules"))) result.push("内容运营"); if (permissions.some((value)=>value.startsWith("model_") )) result.push("模型运营"); if (permissions.some((value)=>value.startsWith("internal_")||value==="roles.manage"||value==="audit.read")) result.push("权限管理"); return result; }
