import { useEffect, useState } from "react";
import type { AdminApi } from "./api";
type Item = { logicalId: string; version: number; name: string; status: string; [key: string]: unknown };
const can = (permissions: string[], code: string) => permissions.includes(code);
export function ContentOperations({ api, permissions }: { api: AdminApi; permissions: string[] }) {
  const [kind, setKind] = useState<"templates" | "rules">("templates"); const [items, setItems] = useState<Item[]>([]); const [editing, setEditing] = useState<Item | undefined>(); const [error, setError] = useState("");
  const read = kind === "templates" ? "content_templates.read" : "review_rules.read"; const edit = kind === "templates" ? "content_templates.edit" : "review_rules.edit"; const publish = kind === "templates" ? "content_templates.publish" : "review_rules.publish";
  async function load() { if (!can(permissions, read)) return; const response = await api.request(`/v1/admin/content/${kind}`); if (!response.ok) { setError("暂时无法读取内容运营配置"); return; } setItems(await response.json() as Item[]); }
  useEffect(() => { void load(); }, [kind, read]);
  return <section className="operations"><div className="tabs"><button className={kind === "templates" ? "selected" : ""} onClick={() => { setKind("templates"); setEditing(undefined); }}>内容模板</button><button className={kind === "rules" ? "selected" : ""} onClick={() => { setKind("rules"); setEditing(undefined); }}>审核规则</button></div>{can(permissions, edit) && <VersionEditor api={api} kind={kind} item={editing} onSaved={async () => { setEditing(undefined); await load(); }} />}{error && <p role="alert">{error}</p>}<ul className="data-list">{items.map(item => <li key={`${item.logicalId}-${item.version}`}><strong>{item.name}</strong><span>版本 {item.version} · {item.status}</span>{can(permissions, edit) && <button onClick={() => setEditing(item)}>编辑</button>}{can(permissions, publish) && item.status === "draft" && <button onClick={() => void publishItem(api, kind, item, load, setError)}>发布</button>}</li>)}</ul></section>;
}
function VersionEditor({ api, kind, item, onSaved }: { api: AdminApi; kind: "templates" | "rules"; item?: Item; onSaved: () => Promise<void> }) { const [name, setName] = useState(""); const [json, setJson] = useState(kind === "templates" ? templateJson : ruleJson); const [error, setError] = useState(""); useEffect(() => { if (!item) { setName(""); setJson(kind === "templates" ? templateJson : ruleJson); return; } const { id, logicalId, version, status, name: itemName, ...body } = item; setName(itemName); setJson(JSON.stringify(body, null, 2)); }, [item, kind]); async function submit(event: React.FormEvent) { event.preventDefault(); try { const payload = { name, ...JSON.parse(json) }; const response = item ? await api.request(`/v1/admin/content/${kind}/${item.logicalId}/draft`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }) : await api.request(`/v1/admin/content/${kind}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(); setError(""); await onSaved(); } catch { setError("请检查名称和版本配置格式"); } } return <form className="editor" onSubmit={event => void submit(event)}><h2>{item ? "编辑版本" : `新建${kind === "templates" ? "模板" : "规则"}`}</h2><label>名称<input value={name} onChange={event => setName(event.target.value)} required /></label><label>版本配置（JSON）<textarea value={json} onChange={event => setJson(event.target.value)} required /></label>{error && <p role="alert">{error}</p>}<button>保存草稿</button></form>; }
async function publishItem(api: AdminApi, kind: string, item: Item, load: () => Promise<void>, fail: (value: string) => void) { const response = await api.request(`/v1/admin/content/${kind}/${item.logicalId}/versions/${item.version}/publish`, { method: "POST" }); if (!response.ok) { fail("发布失败，可能已被其他管理员处理"); return; } await load(); }
const templateJson = '{\n  "content": {"hook":"开头","story":"过程","value":"价值","productAppearance":"产品","cta":"到店","shotRhythm":"快","captionVoiceRequirements":"字幕","prohibitedExpressions":["最好"]},\n  "constraints": {"industryCode":"restaurant","categoryCode":"noodle","persona":"owner","contentType":"story","style":"warm","riskLevel":"low","commercialLevel":1,"priceDiscountEffectRestrictions":["no-price"]},\n  "fallbackScope": {"allowCategoryFallback":true,"allowIndustryFallback":false}\n}';
const ruleJson = '{\n  "ruleType":"absolute_claim",\n  "patterns":["最好"],\n  "semanticCategories":["absolute"],\n  "severity":"block",\n  "platform":"douyin",\n  "scope":"all_copy",\n  "guidance":"改为可验证的事实表达"\n}';
