import { type FormEvent, useEffect, useState } from "react";
import type { AdminApi } from "./api";

type Customer = { id: string; loginName: string; displayName: string; enterpriseId: string; storeId: string; enabled: boolean; passwordChangeRequired: boolean };
const failure = "操作未完成，请检查输入和权限。";

export function CustomerManagement({ api, permissions }: { api: AdminApi; permissions: string[] }) {
  const canRead = permissions.includes("customer_accounts.read"); const canCreate = permissions.includes("customer_accounts.create"); const canReset = permissions.includes("customer_accounts.reset_password"); const canDisable = permissions.includes("customer_accounts.disable"); const canAssign = permissions.includes("model_assignments.manage");
  const [customers, setCustomers] = useState<Customer[]>([]); const [notice, setNotice] = useState("");
  useEffect(() => { if (canRead) void load(); }, [canRead]);
  async function load() { const response = await api.request("/v1/admin/customer-accounts?limit=50"); if (response.ok) setCustomers(((await response.json()) as { items?: Customer[] }).items ?? []); else setNotice(failure); }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; try { const response = await api.request("/v1/admin/customer-accounts", json(Object.fromEntries(new FormData(form)))); const body = await response.json().catch(() => ({})) as { temporaryPassword?: string }; setNotice(response.ok && body.temporaryPassword ? `临时密码（仅显示一次）：${body.temporaryPassword}` : failure); if (response.ok && canRead) await load(); } finally { form.reset(); } }
  async function reset(id: string) { const response = await api.request(`/v1/admin/customer-accounts/${encodeURIComponent(id)}/reset-password`, { method: "POST" }); const body = await response.json().catch(() => ({})) as { temporaryPassword?: string }; setNotice(response.ok && body.temporaryPassword ? `临时密码（仅显示一次）：${body.temporaryPassword}` : failure); }
  async function disable(id: string) { const response = await api.request(`/v1/admin/customer-accounts/${encodeURIComponent(id)}/disable`, { method: "POST" }); setNotice(response.ok ? "客户账号已停用" : failure); if (response.ok && canRead) await load(); }
  return <section><h2>客户账号</h2><p>仅显示账号、归属和状态；不包含客户原始内容、素材、审核记录或对象地址。</p>
    {canCreate && <form onSubmit={event => void create(event)}><h3>新建客户</h3><Input name="mobile" label="手机号" /><Input name="displayName" label="名称" /><Input name="enterpriseId" label="企业 ID" /><Input name="storeId" label="门店 ID" /><label>门店角色<select name="storeRole" defaultValue="owner"><option value="owner">负责人</option><option value="operator">运营人员</option></select></label><button>创建客户</button></form>}
    {canDisable && !canRead && <DirectCustomerDisable api={api} notice={setNotice} />}{canAssign && <DirectModelAssignment api={api} notice={setNotice} />}{notice && <p role="status">{notice}</p>}
    {canRead && <ul className="rows">{customers.map(customer => <li key={customer.id}><span>{customer.displayName} / {customer.loginName} / {customer.enterpriseId}/{customer.storeId}</span><span>{customer.enabled ? "启用" : "停用"}{customer.passwordChangeRequired ? " / 待修改密码" : ""}</span>{canReset && customer.enabled && <button onClick={() => void reset(customer.id)}>重置密码</button>}{canDisable && customer.enabled && <button onClick={() => void disable(customer.id)}>停用账号</button>}{canAssign && <ModelAssignment api={api} customer={customer} notice={setNotice} />}</li>)}</ul>}
  </section>;
}
function ModelAssignment({ api, customer, notice }: { api: AdminApi; customer: Customer; notice: (value: string) => void }) { const [id, setId] = useState(""); const path = `/v1/admin/customer-model-assignments/${encodeURIComponent(customer.enterpriseId)}/${encodeURIComponent(customer.storeId)}`; async function save() { if (!id.trim()) return; try { const response = await api.request(path, json({ modelConfigurationId: id.trim() }, "PUT")); notice(response.ok ? "模型分配已更新。" : failure); } finally { setId(""); } } async function clear() { const response = await api.request(path, { method: "DELETE" }); notice(response.ok ? "模型分配已清除。" : failure); } return <span className="inline"><input aria-label={`${customer.displayName} 模型配置 ID`} value={id} onChange={event => setId(event.target.value)} placeholder="模型配置 ID" /><button onClick={() => void save()}>分配模型</button><button onClick={() => void clear()}>清除分配</button></span>; }
function DirectCustomerDisable({ api, notice }: { api: AdminApi; notice: (value: string) => void }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const accountId = String(new FormData(form).get("accountId") ?? "").trim(); try { const response = await api.request(`/v1/admin/customer-accounts/${encodeURIComponent(accountId)}/disable`, { method: "POST" }); notice(response.ok ? "客户账号已停用" : failure); } catch { notice(failure); } finally { form.reset(); } } return <form onSubmit={event => void submit(event)}><h3>直接停用客户账号</h3><Input name="accountId" label="客户账号 ID" /><button>提交停用</button></form>; }
function DirectModelAssignment({ api, notice }: { api: AdminApi; notice: (value: string) => void }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; try { const values = Object.fromEntries(new FormData(form)); const base = `/v1/admin/customer-model-assignments/${encodeURIComponent(String(values.enterpriseId))}/${encodeURIComponent(String(values.storeId))}`; const response = await api.request(base, values.modelConfigurationId ? json({ modelConfigurationId: values.modelConfigurationId }, "PUT") : { method: "DELETE" }); notice(response.ok ? "模型分配已更新。" : failure); } finally { form.reset(); } } return <form onSubmit={event => void submit(event)}><h3>直接分配或清除模型</h3><Input name="enterpriseId" label="企业 ID" /><Input name="storeId" label="门店 ID" /><label>模型配置 ID（留空即清除）<input name="modelConfigurationId" /></label><button>提交模型分配</button></form>; }
function Input({ name, label }: { name: string; label: string }) { return <label>{label}<input name={name} required /></label>; }
function json(body: unknown, method = "POST"): RequestInit { return { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }; }
