import { type FormEvent, useEffect, useState } from "react";
import type { AdminApi } from "./api";
type Model = { id: string; label: string; provider: string; model: string; baseUrl: string; enabled: boolean; isDefault: boolean; apiKeySuffix?: string };
export function ModelOperations({ api, permissions }: { api: AdminApi; permissions: string[] }) {
  const read = permissions.includes("model_configs.read"); const manage = permissions.includes("model_configs.manage"); const [items, setItems] = useState<Model[]>([]); const [notice, setNotice] = useState("");
  const load = async () => { const response = await api.request("/v1/admin/model-configs"); if (response.ok) setItems(((await response.json()) as { items?: Model[] }).items ?? []); };
  useEffect(() => { if (read) void load(); }, [read]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const response = await api.request("/v1/admin/model-configs", sendForm(form)); setNotice(response.ok ? "模型配置已保存。" : "模型配置未保存。"); if (response.ok) { form.reset(); await load(); } }
  async function action(path: string, init?: RequestInit) { const response = await api.request(path, init); setNotice(response.ok ? "操作已完成。" : "操作未完成。"); if (response.ok) await load(); }
  return <section><h2>模型配置</h2><p>密钥只在提交时传至服务端加密保存，页面不会回读、展示或持久化密钥。</p>{manage && <form onSubmit={(event) => void create(event)}><h3>新增模型配置</h3><Field name="label" label="名称"/><label>供应商<select name="provider" defaultValue="openai_responses"><option value="openai_responses">OpenAI Responses</option><option value="deepseek">DeepSeek</option><option value="qwen">通义千问</option></select></label><Field name="model" label="模型标识"/><Field name="baseUrl" label="HTTPS 地址"/><label>API 密钥<input name="apiKey" type="password" autoComplete="new-password" required /></label><label><input name="enabled" type="checkbox" defaultChecked />启用</label><label><input name="makeDefault" type="checkbox" />设为默认</label><button>保存模型</button></form>}{notice && <p role="status">{notice}</p>}<ul className="rows">{items.map(item => <li key={item.id}><span>{item.label} · {item.provider}/{item.model} · {item.enabled ? "启用" : "停用"}{item.isDefault ? " · 默认" : ""}{item.apiKeySuffix ? ` · 密钥末尾 ${item.apiKeySuffix}` : ""}</span>{manage && <span className="inline"><button onClick={() => void action(`/v1/admin/model-configs/${item.id}/enabled`, send({ enabled: !item.enabled }))}>{item.enabled ? "停用" : "启用"}</button><button onClick={() => void action(`/v1/admin/model-configs/${item.id}/default`, { method: "POST" })}>设为默认</button><Rotate api={api} id={item.id} done={load}/></span>}</li>)}</ul></section>;
}
function Rotate({ api, id, done }: { api: AdminApi; id: string; done: () => Promise<void> }) { const [key, setKey] = useState(""); async function rotate() { if (!key) return; const response = await api.request(`/v1/admin/model-configs/${id}/rotate-key`, send({ apiKey: key })); setKey(""); if (response.ok) await done(); } return <span className="inline"><input aria-label="新 API 密钥" type="password" value={key} onChange={event => setKey(event.target.value)} /><button onClick={() => void rotate()}>轮换密钥</button></span>; }
function Field({ name, label }: { name: string; label: string }) { return <label>{label}<input name={name} required /></label>; }
function send(body: unknown): RequestInit { return { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }; }
function sendForm(form: HTMLFormElement): RequestInit { const value = Object.fromEntries(new FormData(form)); const enabled = form.elements.namedItem("enabled"); const makeDefault = form.elements.namedItem("makeDefault"); return send({ ...value, enabled: enabled instanceof HTMLInputElement && enabled.checked, makeDefault: makeDefault instanceof HTMLInputElement && makeDefault.checked }); }
