import { randomUUID } from "node:crypto";
import type { Database, Queryable } from "../db.js";
import { INTERNAL_PERMISSION_CODES, sanitizeInternalAuditMetadata } from "./rbac.js";

type Row = Record<string, unknown>;
export type AccessRole = { id: string; code: string; displayName: string; enabled: boolean; permissionCodes: string[] };
export type InternalAccount = { id: string; loginName: string; displayName: string; enabled: boolean; roleIds: string[] };
export class AccessManagementValidationError extends Error {}
export class AccessManagementConflictError extends Error {}

export class AccessManagementRepository {
  constructor(private readonly database: Database) {}
  async permissions() { return INTERNAL_PERMISSION_CODES.map(code => ({ code })); }
  async roles(): Promise<AccessRole[]> { const rows = await this.database.query<Row>("SELECT role.id, role.code, role.display_name, role.enabled, permission.permission_code FROM internal_roles role LEFT JOIN internal_role_permissions permission ON permission.role_id=role.id ORDER BY role.code, permission.permission_code"); return roles(rows.rows); }
  async accounts(): Promise<InternalAccount[]> { const rows = await this.database.query<Row>("SELECT DISTINCT account.id, account.login_name, account.display_name, account.enabled, assignment.role_id FROM accounts account JOIN internal_account_roles assignment ON assignment.account_id=account.id AND assignment.enabled=true ORDER BY account.id"); const all = new Map<string, InternalAccount>(); for (const row of rows.rows) { const found = all.get(String(row.id)) ?? { id: String(row.id), loginName: String(row.login_name), displayName: String(row.display_name), enabled: Boolean(row.enabled), roleIds: [] }; if (row.role_id != null) found.roleIds.push(String(row.role_id)); all.set(found.id, found); } return [...all.values()]; }
  async audit(limit = 100) { const result = await this.database.query<Row>("SELECT action_code,target_type,target_id,succeeded,created_at FROM internal_audit_events ORDER BY created_at DESC LIMIT $1", [limit]); return result.rows.map(row => ({ actionCode: String(row.action_code), targetType: String(row.target_type), targetId: String(row.target_id), succeeded: Boolean(row.succeeded), createdAt: String(row.created_at) })); }
  async createRole(input: { code: string; displayName: string; permissionCodes: string[]; actorId: string }): Promise<AccessRole> { validateRole(input); return this.transaction(async client => { const id = randomUUID(); await client.query("INSERT INTO internal_roles (id, code, display_name, enabled) VALUES ($1,$2,$3,true)", [id, input.code, input.displayName]); await replacePermissions(client, id, input.permissionCodes); await audit(client, input.actorId, "internal_role.created", "internal_role", id, { roleCode: input.code, operation: "create", enabled: true }); return { id, code: input.code, displayName: input.displayName, enabled: true, permissionCodes: [...input.permissionCodes].sort() }; }); }
  async updateRole(input: { id: string; displayName: string; enabled: boolean; permissionCodes: string[]; actorId: string }): Promise<AccessRole | undefined> { validateRole(input); return this.transaction(async client => { const existing = await client.query<Row>("SELECT code FROM internal_roles WHERE id=$1 FOR UPDATE", [input.id]); if (!existing.rowCount) return undefined; const code = String(existing.rows[0]!.code); if (code === "super_admin") throw new AccessManagementConflictError(); await client.query("UPDATE internal_roles SET display_name=$2, enabled=$3, updated_at=CURRENT_TIMESTAMP WHERE id=$1", [input.id, input.displayName, input.enabled]); await replacePermissions(client, input.id, input.permissionCodes); await audit(client, input.actorId, "internal_role.updated", "internal_role", input.id, { roleCode: code, operation: "update", enabled: input.enabled }); return { id: input.id, code, displayName: input.displayName, enabled: input.enabled, permissionCodes: [...input.permissionCodes].sort() }; }); }
  async assignRoles(input: { accountId: string; roleIds: string[]; actorId: string }): Promise<InternalAccount | undefined> { validateIds(input.roleIds); return this.transaction(async client => { const account = await client.query<Row>("SELECT id, login_name, display_name, enabled FROM accounts WHERE id=$1 FOR UPDATE", [input.accountId]); if (!account.rowCount) return undefined; const customer = await client.query("SELECT 1 FROM store_memberships WHERE account_id=$1 LIMIT 1", [input.accountId]); if (customer.rowCount) throw new AccessManagementConflictError(); const current = await client.query<Row>("SELECT role.code FROM internal_account_roles assignment JOIN internal_roles role ON role.id=assignment.role_id WHERE assignment.account_id=$1 AND assignment.enabled=true", [input.accountId]); if (current.rows.some(row => String(row.code) === "super_admin")) throw new AccessManagementConflictError(); const roles = await client.query<Row>("SELECT id, code FROM internal_roles WHERE id = ANY($1::text[])", [input.roleIds]); if ((roles.rowCount ?? 0) !== input.roleIds.length || roles.rows.some(row => String(row.code) === "super_admin")) throw new AccessManagementConflictError(); await client.query("UPDATE internal_account_roles SET enabled=false, updated_at=CURRENT_TIMESTAMP WHERE account_id=$1", [input.accountId]); for (const roleId of input.roleIds) await client.query("INSERT INTO internal_account_roles (account_id,role_id,enabled) VALUES($1,$2,true) ON CONFLICT (account_id,role_id) DO UPDATE SET enabled=true,updated_at=CURRENT_TIMESTAMP", [input.accountId, roleId]); await audit(client, input.actorId, "internal_account.roles_assigned", "internal_account", input.accountId, { operation: "assign_roles" }); const a = account.rows[0]!; return { id: String(a.id), loginName: String(a.login_name), displayName: String(a.display_name), enabled: Boolean(a.enabled), roleIds: [...input.roleIds].sort() }; }); }
  private async transaction<T>(work: (client: Queryable) => Promise<T>): Promise<T> { const client = await this.database.connect(); try { await client.query("BEGIN"); const value = await work(client); await client.query("COMMIT"); return value; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
}
function roles(rows: Row[]): AccessRole[] { const all = new Map<string, AccessRole>(); for (const row of rows) { const found = all.get(String(row.id)) ?? { id: String(row.id), code: String(row.code), displayName: String(row.display_name), enabled: Boolean(row.enabled), permissionCodes: [] }; if (row.permission_code != null) found.permissionCodes.push(String(row.permission_code)); all.set(found.id, found); } return [...all.values()]; }
function validateRole(input: { code?: string; displayName: string; permissionCodes: string[] }) { if (input.code !== undefined && (!/^[a-z][a-z0-9_]{2,63}$/.test(input.code) || input.code === "super_admin")) throw new AccessManagementValidationError(); if (!input.displayName?.trim() || input.displayName.trim().length > 100) throw new AccessManagementValidationError(); validateIds(input.permissionCodes); if (!input.permissionCodes.every(code => (INTERNAL_PERMISSION_CODES as readonly string[]).includes(code))) throw new AccessManagementValidationError(); }
function validateIds(values: string[]) { if (!Array.isArray(values) || new Set(values).size !== values.length || !values.every(value => typeof value === "string" && /^[A-Za-z0-9._:-]{1,128}$/.test(value))) throw new AccessManagementValidationError(); }
async function replacePermissions(client: Queryable, roleId: string, permissions: string[]) { await client.query("DELETE FROM internal_role_permissions WHERE role_id=$1", [roleId]); for (const permission of permissions) await client.query("INSERT INTO internal_role_permissions(role_id,permission_code) VALUES($1,$2)", [roleId, permission]); }
async function audit(client: Queryable, actor: string, action: string, type: string, target: string, metadata: Record<string, unknown>) { await client.query("INSERT INTO internal_audit_events(id,actor_account_id,action_code,target_type,target_id,succeeded,metadata_json) VALUES($1,$2,$3,$4,$5,true,$6)", [randomUUID(), actor, action, type, target, JSON.stringify(sanitizeInternalAuditMetadata(metadata))]); }
