import type { FastifyInstance, FastifyRequest } from "fastify";
import { AuthenticationError } from "../auth/tokens.js";
import { AuthorizationError, AuthService } from "../auth/service.js";
import type { Database } from "../db.js";
import { AccessManagementConflictError, AccessManagementRepository, AccessManagementValidationError } from "./access-management.js";

export function registerAccessManagementRoutes(app: FastifyInstance, auth: AuthService, database: Database): void { const repository = new AccessManagementRepository(database);
  app.get("/v1/admin/access/permissions", (r, reply) => run(r, reply, "roles.manage", () => repository.permissions()));
  app.get("/v1/admin/access/roles", (r, reply) => run(r, reply, "roles.manage", () => repository.roles()));
  app.post("/v1/admin/access/roles", (r, reply) => run(r, reply, "roles.manage", actor => { const body = record(r.body); return repository.createRole({ code: code(body.code), displayName: name(body.displayName), permissionCodes: codes(body.permissionCodes), actorId: actor.id }); }, 201));
  app.put("/v1/admin/access/roles/:id", (r, reply) => run(r, reply, "roles.manage", actor => { const body = record(r.body); return repository.updateRole({ id: id(r), displayName: name(body.displayName), enabled: boolean(body.enabled), permissionCodes: codes(body.permissionCodes), actorId: actor.id }); }));
  app.get("/v1/admin/access/accounts", (r, reply) => run(r, reply, "internal_accounts.read", () => repository.accounts()));
  app.get("/v1/admin/access/audit", (r, reply) => run(r, reply, "audit.read", () => repository.audit()));
  app.put("/v1/admin/access/accounts/:id/roles", (r, reply) => run(r, reply, "internal_accounts.manage", actor => repository.assignRoles({ accountId: id(r), roleIds: codes(record(r.body).roleIds), actorId: actor.id })));
  async function run(r: FastifyRequest, reply: { code(status: number): { send(value: unknown): unknown } }, permission: "roles.manage" | "internal_accounts.read" | "internal_accounts.manage" | "audit.read", work: (actor: { id: string }) => Promise<unknown>, created = 200) { try { const result = await auth.requireInternalPermission(bearer(r), permission, work); if (result === undefined) return reply.code(404).send({ error: "Not found" }); return created === 201 ? reply.code(201).send(result) : result; } catch (error) { if (error instanceof AuthenticationError) return reply.code(401).send({ error: "Authentication required" }); if (error instanceof AuthorizationError) return reply.code(403).send({ error: "Forbidden" }); if (error instanceof AccessManagementValidationError) return reply.code(400).send({ error: "Invalid access management input" }); if (error instanceof AccessManagementConflictError) return reply.code(409).send({ error: "Protected internal access state" }); throw error; } }
}
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new AccessManagementValidationError(); return value as Record<string, unknown>; } function id(r: FastifyRequest) { return code(record(r.params).id); } function code(value: unknown) { if (typeof value !== "string" || !/^[A-Za-z0-9._:-]{1,128}$/.test(value)) throw new AccessManagementValidationError(); return value; } function name(value: unknown) { if (typeof value !== "string") throw new AccessManagementValidationError(); return value.trim(); } function boolean(value: unknown) { if (typeof value !== "boolean") throw new AccessManagementValidationError(); return value; } function codes(value: unknown) { if (!Array.isArray(value)) throw new AccessManagementValidationError(); return value.map(code); } function bearer(r: FastifyRequest) { const found = /^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/.exec(r.headers.authorization ?? ""); if (!found) throw new AuthenticationError("Authentication required"); return found[1]!; }
