import { createCipheriv, createDecipheriv, randomBytes, randomUUID } from "node:crypto";
import type { Database, Queryable } from "../db.js";
import { createGenerationService, type GenerationDependencies, type ModelGenerationService } from "../model-providers/generation.js";
import { sanitizeInternalAuditMetadata } from "./rbac.js";

export type ConfiguredModelProvider = "deepseek" | "qwen" | "openai_responses";
export interface ModelConfigurationView { id: string; label: string; provider: ConfiguredModelProvider; model: string; baseUrl: string; apiKeySuffix: string; enabled: boolean; isDefault: boolean; }
export interface ResolvedModelConfiguration extends ModelConfigurationView { apiKey: string; }
export interface ModelGenerationResolver { generationServiceFor(scope: { enterpriseId: string; storeId: string }): Promise<ModelGenerationService>; }
export class ModelConfigurationUnavailableError extends Error { constructor(readonly reason: "missing_encryption_key" | "no_configuration" | "disabled" | "decryption_failed" | "invalid_default" = "no_configuration", message = "Model configuration is unavailable") { super(message); } }
export class ModelConfigurationValidationError extends Error {}

export class ModelConfigurationRepository {
  private readonly key: Buffer;
  constructor(private readonly database: Database, encryptionKey: string | undefined) { this.key = parseEncryptionKey(encryptionKey); }

  async create(input: { label: string; provider: ConfiguredModelProvider; model: string; baseUrl: string; apiKey: string; enabled: boolean; makeDefault: boolean; actorId: string }): Promise<ModelConfigurationView> {
    const normalized = normalize(input); if (normalized.makeDefault && !normalized.enabled) throw new ModelConfigurationValidationError("A default model configuration must be enabled"); const encrypted = encrypt(normalized.apiKey, this.key); const id = randomUUID();
    await this.transaction(async client => {
      if (normalized.makeDefault) await client.query("UPDATE model_configurations SET is_default=false,updated_at=CURRENT_TIMESTAMP WHERE is_default=true");
      await client.query("INSERT INTO model_configurations(id,label,provider,model,base_url,api_key_ciphertext,api_key_nonce,api_key_auth_tag,api_key_suffix,enabled,is_default) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)", [id, normalized.label, normalized.provider, normalized.model, normalized.baseUrl, encrypted.ciphertext, encrypted.nonce, encrypted.authTag, suffix(normalized.apiKey), normalized.enabled, normalized.makeDefault]);
      await audit(client, input.actorId, "model_configuration.created", "model_configuration", id, { modelConfigurationId: id, enabled: normalized.enabled, state: normalized.makeDefault ? "default" : "standard" });
    });
    return (await this.get(id))!;
  }

  async get(id: string): Promise<ModelConfigurationView | undefined> { const result = await this.database.query<Row>("SELECT id,label,provider,model,base_url,api_key_suffix,enabled,is_default FROM model_configurations WHERE id=$1", [id]); return result.rowCount ? view(result.rows[0]!) : undefined; }
  async list(): Promise<ModelConfigurationView[]> { return (await this.database.query<Row>("SELECT id,label,provider,model,base_url,api_key_suffix,enabled,is_default FROM model_configurations ORDER BY label,id")).rows.map(view); }
  async update(input: { id: string; label: string; provider: ConfiguredModelProvider; model: string; baseUrl: string; actorId: string }): Promise<boolean> { const normalized = normalize({ ...input, apiKey: "update-placeholder", enabled: true, makeDefault: false }); return this.transaction(async client => { const result = await client.query("UPDATE model_configurations SET label=$1,provider=$2,model=$3,base_url=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$5 RETURNING id", [normalized.label, normalized.provider, normalized.model, normalized.baseUrl, input.id]); if (!result.rowCount) return false; await audit(client, input.actorId, "model_configuration.updated", "model_configuration", input.id, { modelConfigurationId: input.id, operation: "update" }); return true; }); }

  async rotateKey(input: { id: string; apiKey: string; actorId: string }): Promise<boolean> { const secret = apiKey(input.apiKey); const encrypted = encrypt(secret, this.key); return this.transaction(async client => { const result = await client.query("UPDATE model_configurations SET api_key_ciphertext=$1,api_key_nonce=$2,api_key_auth_tag=$3,api_key_suffix=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$5 RETURNING id", [encrypted.ciphertext, encrypted.nonce, encrypted.authTag, suffix(secret), input.id]); if (!result.rowCount) return false; await audit(client, input.actorId, "model_configuration.key_rotated", "model_configuration", input.id, { modelConfigurationId: input.id, operation: "rotate_key" }); return true; }); }
  async setEnabled(input: { id: string; enabled: boolean; actorId: string }): Promise<boolean> { return this.transaction(async client => { const current = await client.query<Row>("SELECT is_default FROM model_configurations WHERE id=$1 FOR UPDATE", [input.id]); if (!current.rowCount) return false; if (!input.enabled && current.rows[0]!.is_default) throw new ModelConfigurationUnavailableError("invalid_default", "The default model configuration must remain enabled"); await client.query("UPDATE model_configurations SET enabled=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2", [input.enabled, input.id]); await audit(client, input.actorId, "model_configuration.state_changed", "model_configuration", input.id, { modelConfigurationId: input.id, enabled: input.enabled }); return true; }); }
  async makeDefault(input: { id: string; actorId: string }): Promise<boolean> { return this.transaction(async client => { const candidate = await client.query<Row>("SELECT enabled FROM model_configurations WHERE id=$1 FOR UPDATE", [input.id]); if (!candidate.rowCount) return false; if (!candidate.rows[0]!.enabled) throw new ModelConfigurationUnavailableError("invalid_default", "Disabled configurations cannot be default"); await client.query("UPDATE model_configurations SET is_default=false,updated_at=CURRENT_TIMESTAMP WHERE is_default=true"); await client.query("UPDATE model_configurations SET is_default=true,updated_at=CURRENT_TIMESTAMP WHERE id=$1", [input.id]); await audit(client, input.actorId, "model_configuration.default_changed", "model_configuration", input.id, { modelConfigurationId: input.id, state: "default" }); return true; }); }
  async assignCustomer(input: { enterpriseId: string; storeId: string; configurationId: string; actorId: string }): Promise<string> { return this.transaction(async client => { const config = await client.query<Row>("SELECT id,enabled FROM model_configurations WHERE id=$1 FOR UPDATE", [input.configurationId]); if (!config.rowCount || !config.rows[0]!.enabled) throw new ModelConfigurationUnavailableError("disabled"); const id = randomUUID(); await client.query("INSERT INTO customer_model_assignments(id,enterprise_id,store_id,model_configuration_id) VALUES($1,$2,$3,$4) ON CONFLICT (enterprise_id,store_id) DO UPDATE SET model_configuration_id=EXCLUDED.model_configuration_id,updated_at=CURRENT_TIMESTAMP", [id, input.enterpriseId, input.storeId, input.configurationId]); await audit(client, input.actorId, "customer_model_assignment.updated", "customer_model_assignment", `${input.enterpriseId}:${input.storeId}`, { modelConfigurationId: input.configurationId, assignmentMode: "customer_override" }); return input.configurationId; }); }
  async resolveForCustomer(scope: { enterpriseId: string; storeId: string }): Promise<ResolvedModelConfiguration> { const result = await this.database.query<Row>(`SELECT c.* FROM model_configurations c LEFT JOIN customer_model_assignments a ON a.model_configuration_id=c.id AND a.enterprise_id=$1 AND a.store_id=$2 WHERE c.is_default=true OR a.id IS NOT NULL ORDER BY CASE WHEN a.id IS NULL THEN 1 ELSE 0 END LIMIT 1`, [scope.enterpriseId, scope.storeId]); if (!result.rowCount) throw new ModelConfigurationUnavailableError("no_configuration"); if (!result.rows[0]!.enabled) throw new ModelConfigurationUnavailableError("disabled"); const row = result.rows[0]!; return { ...view(row), apiKey: decrypt({ ciphertext: String(row.api_key_ciphertext), nonce: String(row.api_key_nonce), authTag: String(row.api_key_auth_tag) }, this.key) }; }
  async generationServiceFor(scope: { enterpriseId: string; storeId: string }, dependencies?: GenerationDependencies): Promise<ModelGenerationService> { const config = await this.resolveForCustomer(scope); return createGenerationService({ provider: config.provider, model: config.model, apiKey: config.apiKey, baseUrl: config.baseUrl }, dependencies); }
  private async transaction<T>(work: (client: Queryable) => Promise<T>): Promise<T> { const client = await this.database.connect(); try { await client.query("BEGIN"); const result = await work(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
}

export function parseEncryptionKey(value: string | undefined): Buffer { if (!value) throw new ModelConfigurationUnavailableError("missing_encryption_key", "MODEL_CONFIG_ENCRYPTION_KEY is required when model configuration is used"); const key = Buffer.from(value, "base64"); if (key.length !== 32 || key.toString("base64") !== value) throw new ModelConfigurationValidationError("MODEL_CONFIG_ENCRYPTION_KEY must be a base64 encoded 32-byte key"); return key; }
export function validateModelBaseUrl(value: unknown): string { if (typeof value !== "string" || !value.trim()) throw new ModelConfigurationValidationError("Invalid model configuration"); try { const url = new URL(value); if (url.protocol !== "https:" || !url.hostname || url.search || url.hash || url.username || url.password) throw new Error(); return url.toString().replace(/\/$/, ""); } catch { throw new ModelConfigurationValidationError("Invalid model configuration"); } }
function normalize(input: { label: string; provider: ConfiguredModelProvider; model: string; baseUrl: string; apiKey: string; enabled: boolean; makeDefault: boolean }) { if (typeof input.label !== "string" || !input.label.trim() || input.label.trim().length > 120 || !["deepseek", "qwen", "openai_responses"].includes(input.provider) || typeof input.model !== "string" || !input.model.trim() || input.model.trim().length > 256 || typeof input.enabled !== "boolean" || typeof input.makeDefault !== "boolean") throw new ModelConfigurationValidationError("Invalid model configuration"); return { ...input, label: input.label.trim(), model: input.model.trim(), baseUrl: validateModelBaseUrl(input.baseUrl), apiKey: apiKey(input.apiKey) }; }
function apiKey(value: unknown): string { if (typeof value !== "string" || !value.trim() || Buffer.byteLength(value, "utf8") > 4096) throw new ModelConfigurationValidationError("Invalid model configuration"); return value.trim(); }
function suffix(value: string): string { return value.slice(-4); }
function encrypt(value: string, key: Buffer) { const nonce = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key, nonce); return { ciphertext: Buffer.concat([cipher.update(value, "utf8"), cipher.final()]).toString("base64"), nonce: nonce.toString("base64"), authTag: cipher.getAuthTag().toString("base64") }; }
function decrypt(value: { ciphertext: string; nonce: string; authTag: string }, key: Buffer): string { try { const decipher = createDecipheriv("aes-256-gcm", key, Buffer.from(value.nonce, "base64")); decipher.setAuthTag(Buffer.from(value.authTag, "base64")); return Buffer.concat([decipher.update(Buffer.from(value.ciphertext, "base64")), decipher.final()]).toString("utf8"); } catch { throw new ModelConfigurationUnavailableError("decryption_failed"); } }
type Row = Record<string, unknown>;
function view(row: Row): ModelConfigurationView { return { id: String(row.id), label: String(row.label), provider: String(row.provider) as ConfiguredModelProvider, model: String(row.model), baseUrl: String(row.base_url), apiKeySuffix: String(row.api_key_suffix), enabled: Boolean(row.enabled), isDefault: Boolean(row.is_default) }; }
async function audit(database: Queryable, actorId: string, actionCode: string, targetType: string, targetId: string, metadata: Record<string, unknown>) { await database.query("INSERT INTO internal_audit_events(id,actor_account_id,action_code,target_type,target_id,succeeded,metadata_json) VALUES($1,$2,$3,$4,$5,true,$6)", [randomUUID(), actorId, actionCode, targetType, targetId, JSON.stringify(sanitizeInternalAuditMetadata(metadata))]); }
