import type { FastifyInstance, FastifyRequest } from "fastify";
import { AuthenticationError } from "../auth/tokens.js";
import { AuthorizationError, AuthService } from "../auth/service.js";
import type { Database } from "../db.js";
import { ModelConfigurationRepository, ModelConfigurationUnavailableError, ModelConfigurationValidationError } from "./model-configs.js";

export async function registerModelConfigurationRoutes(app: FastifyInstance, auth: AuthService, database: Database, encryptionKey: string | undefined): Promise<void> {
  const repository = () => new ModelConfigurationRepository(database, encryptionKey);
  app.get("/v1/admin/model-configs", async (request, reply) => run(request, reply, "model_configs.read", () => repository().list()));
  app.get("/v1/admin/model-configs/:id", async (request, reply) => run(request, reply, "model_configs.read", async () => { const found = await repository().get(identifier(params(request).id)); return found ?? reply.code(404).send({ error: "Model configuration not found" }); }));
  app.post("/v1/admin/model-configs", async (request, reply) => run(request, reply, "model_configs.manage", async actor => { const body = record(request.body); const created = await repository().create({ label: text(body.label), provider: provider(body.provider), model: text(body.model), baseUrl: text(body.baseUrl), apiKey: text(body.apiKey), enabled: bool(body.enabled), makeDefault: optionalBool(body.makeDefault, false), actorId: actor.id }); return reply.code(201).send(created); }));
  app.put("/v1/admin/model-configs/:id", async (request, reply) => run(request, reply, "model_configs.manage", async actor => { const body = record(request.body); return (await repository().update({ id: identifier(params(request).id), label: text(body.label), provider: provider(body.provider), model: text(body.model), baseUrl: text(body.baseUrl), actorId: actor.id })) ? reply.code(204).send() : reply.code(404).send({ error: "Model configuration not found" }); }));
  app.post("/v1/admin/model-configs/:id/rotate-key", async (request, reply) => run(request, reply, "model_configs.manage", async actor => (await repository().rotateKey({ id: identifier(params(request).id), apiKey: text(record(request.body).apiKey), actorId: actor.id })) ? reply.code(204).send() : reply.code(404).send({ error: "Model configuration not found" })));
  app.post("/v1/admin/model-configs/:id/enabled", async (request, reply) => run(request, reply, "model_configs.manage", async actor => (await repository().setEnabled({ id: identifier(params(request).id), enabled: bool(record(request.body).enabled), actorId: actor.id })) ? reply.code(204).send() : reply.code(404).send({ error: "Model configuration not found" })));
  app.post("/v1/admin/model-configs/:id/default", async (request, reply) => run(request, reply, "model_configs.manage", async actor => (await repository().makeDefault({ id: identifier(params(request).id), actorId: actor.id })) ? reply.code(204).send() : reply.code(404).send({ error: "Model configuration not found" })));
  app.put("/v1/admin/customer-model-assignments/:enterpriseId/:storeId", async (request, reply) => run(request, reply, "model_assignments.manage", async actor => { const p = params(request); const configurationId = await repository().assignCustomer({ enterpriseId: identifier(p.enterpriseId), storeId: identifier(p.storeId), configurationId: identifier(record(request.body).modelConfigurationId), actorId: actor.id }); return { modelConfigurationId: configurationId }; }));
  app.delete("/v1/admin/customer-model-assignments/:enterpriseId/:storeId", async (request, reply) => run(request, reply, "model_assignments.manage", async actor => { const p = params(request); await repository().clearCustomerAssignment({ enterpriseId: identifier(p.enterpriseId), storeId: identifier(p.storeId), actorId: actor.id }); return reply.code(204).send(); }));
  async function run(request: FastifyRequest, reply: { code(status: number): { send(value?: unknown): unknown } }, permission: "model_configs.read" | "model_configs.manage" | "model_assignments.manage", work: (actor: { id: string; displayName: string }) => Promise<unknown>) { try { return await auth.requireInternalPermission(bearer(request), permission, work); } catch (error) { if (error instanceof AuthenticationError) return reply.code(401).send({ error: "Authentication required" }); if (error instanceof AuthorizationError) return reply.code(403).send({ error: "Forbidden" }); if (error instanceof ModelConfigurationValidationError) return reply.code(400).send({ error: "Invalid model configuration" }); if (error instanceof ModelConfigurationUnavailableError) return reply.code(422).send({ error: "Model configuration is unavailable" }); throw error; } }
}
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new ModelConfigurationValidationError("Invalid model configuration"); return value as Record<string, unknown>; }
function params(request: FastifyRequest): Record<string, unknown> { return record(request.params); }
function text(value: unknown): string { if (typeof value !== "string") throw new ModelConfigurationValidationError("Invalid model configuration"); return value; }
function bool(value: unknown): boolean { if (typeof value !== "boolean") throw new ModelConfigurationValidationError("Invalid model configuration"); return value; }
function optionalBool(value: unknown, fallback: boolean): boolean { return value === undefined ? fallback : bool(value); }
function provider(value: unknown): "deepseek" | "qwen" | "openai_responses" { if (value === "deepseek" || value === "qwen" || value === "openai_responses") return value; throw new ModelConfigurationValidationError("Invalid model configuration"); }
function identifier(value: unknown): string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(value)) throw new ModelConfigurationValidationError("Invalid model configuration"); return value; }
function bearer(request: FastifyRequest): string { const match = /^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/.exec(request.headers.authorization ?? ""); if (!match) throw new AuthenticationError("Authentication required"); return match[1]!; }
