import { createHash, randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { Pool } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { DatabaseRenderWorkerRepository, RenderRepository } from "../src/video-editing/render-repository.js";

const url = process.env.REAL_POSTGRES_TEST_URL;
const scope = { enterpriseId: "pg-render-ent", storeId: "pg-render-store", actorId: "pg-render-customer" };
describe.skipIf(!url)("storyboard render PostgreSQL concurrency", () => {
  const schema = `render_pg_${randomUUID().replace(/-/g, "")}`; let admin: Pool; let pool: Pool; let input: { taskId: string; shotListId: string; projectId: string };
  beforeAll(async () => { admin = new Pool({ connectionString: url }); await admin.query(`CREATE SCHEMA ${schema}`); pool = new Pool({ connectionString: url, options: `-c search_path=${schema}` }); for (const file of ["001_imports.sql", "013_content_planning_profile.sql", "014_content_templates_rules.sql", "015_operator_accounts_sessions.sql", "016_operator_content_versions.sql", "017_douyin_official_connections.sql", "018_content_planning_workflow.sql", "019_storyboard_media_assets.sql", "020_storyboard_media_asset_hardening.sql", "021_storyboard_projects.sql", "022_storyboard_render_jobs.sql", "023_storyboard_render_lifecycle.sql", "024_storyboard_render_artifacts.sql", "025_storyboard_render_leases.sql"]) await pool.query(await readFile(new URL(`../migrations/${file}`, import.meta.url), "utf8")); input = await seed(pool); }, 30_000);
  afterAll(async () => { await pool?.end(); await admin?.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`); await admin?.end(); });
  it("allows exactly one concurrent admission for a project", async () => {
    const repository = new RenderRepository(pool); const results = await Promise.allSettled([repository.enqueue(scope, { ...input, kind: "final" }), repository.enqueue(scope, { ...input, kind: "final" })]);
    expect(results.filter(result => result.status === "fulfilled")).toHaveLength(1);
    expect((await pool.query("SELECT count(*)::int AS count FROM storyboard_render_jobs WHERE state IN ('queued','processing')")).rows).toEqual([{ count: 1 }]);
  });
  it("rolls back the succeeded transition and every artifact when an artifact insert fails", async () => {
    const id = randomUUID();
    await pool.query("INSERT INTO storyboard_render_jobs(id,enterprise_id,store_id,task_id,shot_list_id,project_id,project_version,kind,state,lease_token,lease_expires_at) VALUES($1,$2,$3,$4,$5,$6,1,'final','processing','lease',CURRENT_TIMESTAMP + interval '1 hour')", [id, scope.enterpriseId, scope.storeId, input.taskId, input.shotListId, input.projectId]);
    const repository = new DatabaseRenderWorkerRepository(pool, () => new Date());
    await expect(repository.succeed(id, { outputExpiresAt: new Date("2027-02-11T00:00:00.000Z"), coverCandidates: [{ positionSeconds: 1 }, { positionSeconds: 2 }, { positionSeconds: 3 }], artifacts: [{ objectKey: `atomic-${id}`, kind: "video" }, { objectKey: `atomic-${id}`, kind: "cover" }] }, "lease")).rejects.toThrow();
    expect((await pool.query("SELECT state,output_object_key FROM storyboard_render_jobs WHERE id=$1", [id])).rows[0]).toMatchObject({ state: "processing", output_object_key: null });
    expect((await pool.query("SELECT count(*)::int AS count FROM storyboard_render_artifacts WHERE render_job_id=$1", [id])).rows).toEqual([{ count: 0 }]);
  });
});
async function seed(pool: Pool) { const taskId = randomUUID(), topicId = randomUUID(), copyId = randomUUID(), shotListId = randomUUID(), assetId = randomUUID(); const projectId = createHash("sha256").update(`${scope.enterpriseId}:${scope.storeId}:${taskId}:${shotListId}:${scope.actorId}`).digest("hex"); await pool.query("INSERT INTO content_tasks(id,enterprise_id,store_id,actor_id,profile_version,profile_snapshot_json,stage_snapshot_json,template_snapshot_json,persona,content_type,style,commercial_level,status,confirmed_copy_id) VALUES($1,$2,$3,$4,1,'{}','{}','[]','owner','story','sincere',1,'copy_confirmed',$5)", [taskId, scope.enterpriseId, scope.storeId, scope.actorId, copyId]); await pool.query("INSERT INTO content_task_topics(id,task_id,position,title,angle,product_reference,goal_reference,commercial_level) VALUES($1,$2,1,'title','angle','product','goal',1)", [topicId, taskId]); await pool.query("INSERT INTO content_task_copies(id,task_id,topic_id,position,title,body,strategy,product_reference,goal_reference,commercial_level,status,confirmed_at) VALUES($1,$2,$3,1,'title','body','strategy','product','goal',1,'confirmed',CURRENT_TIMESTAMP)", [copyId, taskId, topicId]); await pool.query("INSERT INTO content_task_shot_lists(id,task_id,copy_id,shots_json) VALUES($1,$2,$3,'[]')", [shotListId, taskId, copyId]); await pool.query("INSERT INTO storyboard_projects(id,enterprise_id,store_id,task_id,shot_list_id,actor_id) VALUES($1,$2,$3,$4,$5,$6)", [projectId, scope.enterpriseId, scope.storeId, taskId, shotListId, scope.actorId]); await pool.query("INSERT INTO storyboard_project_versions(id,project_id,version,status,slots_json) VALUES($1,$2,1,'final','[]')", [randomUUID(), projectId]); await pool.query("INSERT INTO storyboard_media_assets(id,enterprise_id,store_id,task_id,shot_list_id,project_id,object_key,content_type,expected_size_bytes,size_bytes,duration_seconds,status,expires_at) VALUES($1,$2,$3,$4,$5,$6,'source','video/mp4',1,1,1,'accepted',CURRENT_TIMESTAMP + interval '30 days')", [assetId, scope.enterpriseId, scope.storeId, taskId, shotListId, projectId]); return { taskId, shotListId, projectId }; }
