import { useEffect, useState } from 'react';
import { emptyRule, type Rule, type RuleInput } from './types';

export function RuleEditor({ rule, onSave, onPublish, onDisable, onPreview }: { rule?: Rule; onSave(id: string | undefined, input: RuleInput): Promise<unknown>; onPublish(id: string, version: number): Promise<unknown>; onDisable(id: string, version: number): Promise<unknown>; onPreview(input: RuleInput, text: string): Promise<{ matches?: Array<{ pattern: string; guidance: string }> }> }) {
  const [value, setValue] = useState<RuleInput>(rule ?? emptyRule()); const [previewText, setPreviewText] = useState(''); const [matches, setMatches] = useState<Array<{ pattern: string; guidance: string }>>([]); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const locked = rule?.status !== undefined && rule.status !== 'draft';
  useEffect(() => { setValue(rule ?? emptyRule()); setMatches([]); setPreviewText(''); }, [rule]);
  const input = (key: keyof RuleInput, label: string, textarea = false) => <label>{label}{textarea ? <textarea disabled={locked} value={String(value[key])} onChange={(event) => setValue({ ...value, [key]: event.target.value })} /> : <input disabled={locked} value={String(value[key])} onChange={(event) => setValue({ ...value, [key]: event.target.value })} />}</label>;
  const list = (key: 'patterns' | 'semanticCategories', label: string) => <label>{label}<textarea disabled={locked} value={value[key].join('\n')} onChange={(event) => setValue({ ...value, [key]: event.target.value.split('\n').map((item) => item.trim()).filter(Boolean) })} /></label>;
  const valid = () => Boolean(value.name.trim() && value.ruleType.trim() && value.platform.trim() && value.scope.trim() && value.guidance.trim() && value.patterns.length && value.semanticCategories.length);
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(undefined); try { await action(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Request failed.'); } finally { setBusy(false); } }
  return <section className="editor" aria-label="Rule editor">{locked && <p className="notice">Published versions are immutable. Create the next draft to edit.</p>}
    {input('name', 'Rule name')}{input('ruleType', 'Rule type')}{list('patterns', 'Literal patterns (one per line)')}{list('semanticCategories', 'Semantic categories (one per line)')}
    <label>Severity<select disabled={locked} value={value.severity} onChange={(event) => setValue({ ...value, severity: event.target.value as RuleInput['severity'] })}>{['block', 'high', 'warning', 'notice'].map((severity) => <option key={severity}>{severity}</option>)}</select></label>
    {input('platform', 'Platform')}{input('scope', 'Scope')}{input('guidance', 'Customer-facing guidance', true)}
    <fieldset><legend>Transient test preview</legend><label>Preview text<textarea value={previewText} onChange={(event) => setPreviewText(event.target.value)} /></label><button disabled={busy || !valid() || !previewText} onClick={() => void run(async () => setMatches((await onPreview(value, previewText)).matches ?? []) )}>Test rule</button>{matches.length > 0 && <ul aria-label="Preview matches">{matches.map((match, index) => <li key={`${match.pattern}-${index}`}><span>{match.pattern}</span>: <span>{match.guidance}</span></li>)}</ul>}{matches.length === 0 && previewText && <p>No matches.</p>}</fieldset>
    {error && <p role="alert">{error}</p>}<div className="actions">{locked ? <button disabled={busy} onClick={() => void run(() => onSave(rule?.logicalId, value))}>Create next draft</button> : <button disabled={busy || !valid()} onClick={() => void run(() => onSave(rule?.logicalId, value))}>Save draft</button>}<button disabled={busy || rule?.status !== 'draft'} onClick={() => rule && void run(() => onPublish(rule.logicalId, rule.version))}>Publish</button><button className="danger" disabled={busy || rule?.status !== 'published'} onClick={() => rule && void run(() => onDisable(rule.logicalId, rule.version))}>Disable</button></div>
  </section>;
}
