import { useEffect, useRef, useState } from 'react';
import { OperatorApiError, type OperatorApi } from '../api';
import { TemplateEditor } from './template-editor';
import { emptyTemplate, type Template, type TemplateInput } from './types';

export function TemplateList({ api }: { api: Pick<OperatorApi, 'request'> }) {
  const [items, setItems] = useState<Template[]>([]); const [selected, setSelected] = useState<Template>(); const [versions, setVersions] = useState<Template[]>([]); const [history, setHistory] = useState<Array<{ version: number; eventType: string }>>([]); const [state, setState] = useState<'loading' | 'ready' | 'forbidden' | 'failed'>('loading'); const [message, setMessage] = useState<string>(); const [nameFilter, setNameFilter] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [industryFilter, setIndustryFilter] = useState(''); const [categoryFilter, setCategoryFilter] = useState(''); const selectionRequest = useRef(0);
  async function load() { setState('loading'); try { const result = await api.request('GET', '/v1/operator-content/templates'); setItems(Array.isArray(result) ? result as Template[] : []); setState('ready'); } catch (cause) { setState(cause instanceof OperatorApiError || (typeof cause === 'object' && cause !== null && 'status' in cause && (cause as { status: unknown }).status === 403) ? 'forbidden' : 'failed'); } }
  useEffect(() => { void load(); }, []);
  async function choose(item: Template) { const request = ++selectionRequest.current; try { const [detail, versionList, audit] = await Promise.all([api.request('GET', `/v1/operator-content/templates/${item.logicalId}/versions/${item.version}`) as Promise<Template>, api.request('GET', `/v1/operator-content/templates/${item.logicalId}/versions`) as Promise<Template[]>, api.request('GET', `/v1/operator-content/templates/${item.logicalId}/history`) as Promise<{ events?: Array<{ version: number; eventType: string }> }>]); if (request !== selectionRequest.current) return; setSelected(detail); setVersions(versionList); setHistory(audit.events ?? []); } catch { if (request === selectionRequest.current) setMessage('Unable to load version history.'); } }
  async function refreshMutation(intent: number, item: Template, message: string) { await load(); if (selectionRequest.current === intent) { await choose(item); setMessage(message); } }
  async function save(id: string | undefined, input: TemplateInput) { const intent = selectionRequest.current; const item = id ? await api.request('PUT', `/v1/operator-content/templates/${id}/draft`, input) as Template : await api.request('POST', '/v1/operator-content/templates', input) as Template; await refreshMutation(intent, item, 'Draft saved.'); }
  async function transition(action: 'publish' | 'disable', id: string, version: number) { const intent = selectionRequest.current; const item = await api.request('POST', `/v1/operator-content/templates/${id}/versions/${version}/${action}`) as Template; await refreshMutation(intent, item, action === 'publish' ? 'Version published.' : 'Version disabled.'); }
  if (state === 'loading') return <p className="state">Loading templates...</p>;
  if (state === 'forbidden') return <section className="state"><p>Access is unavailable.</p><button onClick={() => void load()}>Retry</button></section>;
  if (state === 'failed') return <section className="state"><p>Templates could not be loaded.</p><button onClick={() => void load()}>Retry</button></section>;
  const filtered = items.filter((item) => item.name.toLowerCase().includes(nameFilter.toLowerCase()) && (!statusFilter || item.status === statusFilter) && (!industryFilter || item.constraints.industryCode === industryFilter) && (!categoryFilter || item.constraints.categoryCode === categoryFilter));
  return <div className="content-manager"><section className="library-list"><div className="list-heading"><h2>Templates</h2><button onClick={() => { ++selectionRequest.current; setSelected(undefined); setVersions([]); setHistory([]); }}>New template</button></div><div className="filters"><label>Template name filter<input value={nameFilter} onChange={(event) => setNameFilter(event.target.value)} /></label><label>Template status<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">All</option>{['draft', 'published', 'disabled'].map((value) => <option key={value}>{value}</option>)}</select></label><label>Industry filter<input value={industryFilter} onChange={(event) => setIndustryFilter(event.target.value)} /></label><label>Category filter<input value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)} /></label></div>{filtered.length === 0 ? <p>No templates yet.</p> : <ul>{filtered.map((item) => <li key={item.logicalId}><button className={selected?.logicalId === item.logicalId ? 'selected' : ''} onClick={() => void choose(item)}><span>{item.name}</span><small>v{item.version} · {item.status}</small></button></li>)}</ul>}</section><section className="detail"><h2>{selected ? `${selected.name} v${selected.version}` : 'New template'}</h2>{message && <p role="status">{message}</p>}<TemplateEditor template={selected} onSave={save} onPublish={(id, version) => transition('publish', id, version)} onDisable={(id, version) => transition('disable', id, version)} />{versions.length > 0 && <section aria-label="Template version history"><h3>Version history</h3><ul>{versions.map((item) => <li key={item.version}><button onClick={() => void choose(item)}>v{item.version} · {item.status}{selected?.version === item.version ? ' · selected' : ''}</button></li>)}</ul><h3>Audit history</h3><ul>{history.map((event, index) => <li key={`${event.version}-${event.eventType}-${index}`}>v{event.version} · {event.eventType}</li>)}</ul></section>}</section></div>;
}
