import { useEffect, useState } from 'react';
import { emptyTemplate, type Template, type TemplateInput } from './types';
import { OperatorApiError } from '../api';

export function TemplateEditor({ template, onSave, onPublish, onDisable }: { template?: Template; onSave(id: string | undefined, input: TemplateInput): Promise<unknown>; onPublish(id: string, version: number): Promise<unknown>; onDisable(id: string, version: number): Promise<unknown> }) {
  const [value, setValue] = useState<TemplateInput>(template ?? emptyTemplate());
  const [error, setError] = useState<string>();
  const [busy, setBusy] = useState(false);
  const locked = template?.status !== undefined && template.status !== 'draft';
  useEffect(() => setValue(template ?? emptyTemplate()), [template]);
  const field = (group: 'content' | 'constraints', key: string, label: string, textarea = true) => <label>{label}{textarea ? <textarea disabled={locked} value={String(value[group][key] ?? '')} onChange={(event) => setValue({ ...value, [group]: { ...value[group], [key]: event.target.value } })} /> : <input disabled={locked} value={String(value[group][key] ?? '')} onChange={(event) => setValue({ ...value, [group]: { ...value[group], [key]: event.target.value } })} />}</label>;
  const list = (group: 'content' | 'constraints', key: string, label: string) => <label>{label}<textarea disabled={locked} value={Array.isArray(value[group][key]) ? (value[group][key] as string[]).join('\n') : ''} onChange={(event) => setValue({ ...value, [group]: { ...value[group], [key]: event.target.value.split('\n').map((item) => item.trim()).filter(Boolean) } })} /></label>;
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(undefined); try { await action(); } catch (cause) { setError(cause instanceof OperatorApiError && cause.status === 409 ? 'This version changed on the server. Your draft remains here; refresh version history before retrying.' : cause instanceof Error ? cause.message : 'Request failed.'); } finally { setBusy(false); } }
  function valid() { return value.name.trim() && ['hook', 'story', 'value', 'productAppearance', 'cta', 'shotRhythm', 'captionVoiceRequirements'].every((key) => String(value.content[key] ?? '').trim()) && Array.isArray(value.content.prohibitedExpressions) && value.content.prohibitedExpressions.length && ['industryCode', 'categoryCode', 'persona', 'contentType', 'style', 'riskLevel'].every((key) => String(value.constraints[key] ?? '').trim()) && Array.isArray(value.constraints.priceDiscountEffectRestrictions) && value.constraints.priceDiscountEffectRestrictions.length; }
  return <section className="editor" aria-label="Template editor">
    {locked && <p className="notice">Published versions are immutable. Saving creates the next draft version.</p>}
    <label>Template name<input disabled={locked} value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /></label>
    <div className="editor-grid">{field('content', 'hook', 'Hook')}{field('content', 'story', 'Story progression')}{field('content', 'value', 'Emotional or value point')}{field('content', 'productAppearance', 'Product appearance')}{field('content', 'cta', 'CTA')}{field('content', 'shotRhythm', 'Shot rhythm')}{field('content', 'captionVoiceRequirements', 'Caption and voice requirements')}{list('content', 'prohibitedExpressions', 'Prohibited expressions (one per line)')}{field('constraints', 'industryCode', 'Industry code', false)}{field('constraints', 'categoryCode', 'Category code', false)}{field('constraints', 'persona', 'Persona', false)}{field('constraints', 'contentType', 'Content type', false)}{field('constraints', 'style', 'Style', false)}{field('constraints', 'riskLevel', 'Risk level', false)}{list('constraints', 'priceDiscountEffectRestrictions', 'Price, discount, and effect restrictions (one per line)')}</div>
    <label>Commercial level<select disabled={locked} value={String(value.constraints.commercialLevel)} onChange={(event) => setValue({ ...value, constraints: { ...value.constraints, commercialLevel: Number(event.target.value) } })}>{[0, 1, 2, 3].map((level) => <option key={level} value={level}>{level}</option>)}</select></label>
    <label><input type="checkbox" disabled={locked} checked={value.fallbackScope.allowCategoryFallback} onChange={(event) => setValue({ ...value, fallbackScope: { ...value.fallbackScope, allowCategoryFallback: event.target.checked } })} /> Allow category fallback</label>
    <label><input type="checkbox" disabled={locked} checked={value.fallbackScope.allowIndustryFallback} onChange={(event) => setValue({ ...value, fallbackScope: { ...value.fallbackScope, allowIndustryFallback: event.target.checked } })} /> Allow industry fallback</label>
    {error && <p role="alert">{error}</p>}
    <div className="actions">{locked ? <button disabled={busy} onClick={() => void run(() => onSave(template?.logicalId, value))}>Create next draft</button> : <button disabled={busy || !valid()} onClick={() => void run(() => onSave(template?.logicalId, value))}>Save draft</button>}<button disabled={busy || template?.status !== 'draft'} onClick={() => template && void run(() => onPublish(template.logicalId, template.version))}>Publish</button><button className="danger" disabled={busy || template?.status !== 'published'} onClick={() => template && void run(() => onDisable(template.logicalId, template.version))}>Disable</button></div>
  </section>;
}
