import { randomUUID } from "node:crypto";
import type { FastifyInstance, FastifyRequest } from "fastify";
import type { Database } from "../db.js";
import { ForbiddenError } from "../imports/repository.js";
import type { TrustedContext } from "../imports/service.js";
import { copyDraftsSchema, shotListSchema, topicArraySchema, type ModelGenerationService } from "../model-providers/generation.js";
import { CopyReviewService } from "./review-service.js";

type Row = Record<string, unknown>;
class WorkflowError extends Error { constructor(message: string, readonly status = 422, readonly findings?: unknown[]) { super(message); } }

export async function registerWorkflowRoutes(app: FastifyInstance, database: Database, resolve: (request: FastifyRequest) => Promise<TrustedContext | undefined>, generator?: ModelGenerationService): Promise<void> {
  if (!generator) throw new Error("workflow routes require a generation service");
  const review = new CopyReviewService(database, generator);
  app.addHook("onRequest", async (request, reply) => { const context = await resolve(request); if (!context) return reply.code(403).send({ error: "No trusted request context" }); request.trustedContext = context; });
  const scoped = (request: FastifyRequest) => { const storeId = String((request.params as Row).storeId ?? ""); const context = request.trustedContext; if (!context || context.storeId !== storeId) throw new ForbiddenError("Store is outside trusted request context"); return context; };
  const body = (request: FastifyRequest): Row => { if (!request.body || typeof request.body !== "object" || Array.isArray(request.body)) throw new WorkflowError("Request body must be an object"); return request.body as Row; };
  const task = async (request: FastifyRequest) => { const context = scoped(request); const id = String((request.params as Row).id ?? ""); const found = await database.query<Row>("SELECT * FROM content_tasks WHERE id=$1 AND enterprise_id=$2 AND store_id=$3", [id, context.enterpriseId, context.storeId]); if (!found.rowCount) throw new WorkflowError("Content task not found", 404); return found.rows[0]; };
  app.post("/v1/stores/:storeId/content-tasks", async (request, reply) => { const context = scoped(request); const input = body(request); const required = ["persona", "contentType", "style"]; if (required.some((key) => typeof input[key] !== "string" || !String(input[key]).trim()) || !Number.isSafeInteger(input.commercialLevel) || Number(input.commercialLevel) < 0 || Number(input.commercialLevel) > 3 || (input.inspiration !== undefined && typeof input.inspiration !== "string")) throw new WorkflowError("persona, contentType, style, and commercialLevel are required");
    const profile = await database.query<Row>("SELECT * FROM store_content_profile_versions WHERE enterprise_id=$1 AND store_id=$2 ORDER BY version DESC LIMIT 1", [context.enterpriseId, context.storeId]); if (!profile.rowCount) throw new WorkflowError("Content profile is required", 409);
    const stage = await database.query<Row>("SELECT * FROM store_operating_stages WHERE enterprise_id=$1 AND store_id=$2 ORDER BY effective_date DESC LIMIT 1", [context.enterpriseId, context.storeId]); if (!stage.rowCount) throw new WorkflowError("Operating stage is required", 409);
    const templateRows=await database.query<Row>("SELECT * FROM operator_content_template_versions WHERE status='published' ORDER BY logical_id,version DESC"); const templates=templateRows.rows.filter(row=>matchesTemplate(row,profile.rows[0],input));
    const id = randomUUID(); const row = await database.query<Row>("INSERT INTO content_tasks(id,enterprise_id,store_id,actor_id,profile_version,profile_snapshot_json,stage_snapshot_json,template_snapshot_json,inspiration,persona,content_type,style,commercial_level,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'topic_draft') RETURNING *", [id, context.enterpriseId, context.storeId, context.actorId, profile.rows[0].version, JSON.stringify(profile.rows[0]), JSON.stringify(stage.rows[0]), JSON.stringify(templates), optional(input.inspiration), String(input.persona).trim(), String(input.contentType).trim(), String(input.style).trim(), input.commercialLevel]); return reply.code(201).send(taskJson(row.rows[0])); });
  app.post("/v1/stores/:storeId/content-tasks/:id/topics/generate", async (request, reply) => { const item = await task(request); const output = await generator.generateStructured({ requestId: String(item.id), promptVersion: "content-topic-v1", commercialLevel: Number(item.commercial_level) as 0|1|2|3, input: generationInput(item), schema: topicArraySchema }); if (output.output.length !== 3) throw new WorkflowError("Topic generation must return exactly three topics", 502); const client=await database.connect(); try{await client.query("BEGIN");await client.query("SELECT id FROM content_tasks WHERE id=$1 FOR UPDATE",[item.id]);const existing=await client.query<Row>("SELECT * FROM content_task_topics WHERE task_id=$1 ORDER BY position",[item.id]);if(existing.rowCount){await client.query("COMMIT");return reply.code(201).send(existing.rows.map(topicJson));}const saved:Row[]=[];for(const [index,topic] of output.output.entries())saved.push((await client.query<Row>("INSERT INTO content_task_topics(id,task_id,position,title,angle,product_reference,goal_reference,commercial_level) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *",[randomUUID(),item.id,index+1,topic.title,topic.angle,topic.productReference,topic.goalReference,topic.commercialLevel])).rows[0]);await client.query("COMMIT");return reply.code(201).send(saved.map(topicJson));}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();} });
  app.post("/v1/stores/:storeId/content-tasks/:id/topics/:topicId/copies/generate", async (request, reply) => {
    const item = await task(request); const topicId = String((request.params as Row).topicId ?? "");
    const topic = await database.query<Row>("SELECT * FROM content_task_topics WHERE id=$1 AND task_id=$2", [topicId, item.id]); if (!topic.rowCount) throw new WorkflowError("Topic not found", 404);
    const output = await generator.generateStructured({ requestId: `${item.id}:${topicId}`, promptVersion: "content-copy-v1", commercialLevel: Number(item.commercial_level) as 0|1|2|3, input: { ...generationInput(item), topic: topicJson(topic.rows[0]) }, schema: copyDraftsSchema });
    const client = await database.connect();
    try {
      await client.query("BEGIN");
      await client.query("SELECT id FROM content_tasks WHERE id=$1 FOR UPDATE", [item.id]);
      const old = await client.query<Row>("SELECT * FROM content_task_copies WHERE task_id=$1 AND topic_id=$2 ORDER BY position", [item.id, topicId]);
      if (old.rowCount) { await client.query("COMMIT"); return reply.code(201).send(old.rows.map(copyJson)); }
      const saved: Row[] = [];
      for (const [index, generated] of output.output.entries()) {
        const copy = (await client.query<Row>("INSERT INTO content_task_copies(id,task_id,topic_id,position,title,body,strategy,product_reference,goal_reference,commercial_level) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *", [randomUUID(), item.id, topicId, index + 1, generated.title, generated.body, generated.strategy, generated.productReference, generated.goalReference, generated.commercialLevel])).rows[0];
        await client.query("INSERT INTO content_task_copy_versions(id,copy_id,version,title,body) VALUES($1,$2,1,$3,$4)", [randomUUID(), copy.id, copy.title, copy.body]);
        saved.push(copy);
      }
      await client.query("COMMIT");
      return reply.code(201).send(saved.map(copyJson));
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  });
  app.put("/v1/stores/:storeId/content-tasks/:id/copies/:copyId", async request => { const item = await task(request); const input = body(request); if (![input.title,input.body].every(x => typeof x === "string" && x.trim())) throw new WorkflowError("title and body are required"); const original=await database.query<Row>("SELECT * FROM content_task_copies WHERE id=$1 AND task_id=$2",[String((request.params as Row).copyId),item.id]); if(!original.rowCount)throw new WorkflowError("Editable draft copy not found",409); const result = await database.query<Row>("UPDATE content_task_copies SET title=$3,body=$4,version=version+1 WHERE id=$1 AND task_id=$2 RETURNING *", [String((request.params as Row).copyId), item.id, String(input.title).trim(), String(input.body).trim()]); const copy=result.rows[0]; await database.query("INSERT INTO content_task_copy_versions(id,copy_id,version,title,body) VALUES($1,$2,$3,$4,$5)",[randomUUID(),copy.id,copy.version,copy.title,copy.body]); return copyJson(copy); });
  app.post("/v1/stores/:storeId/content-tasks/:id/copies/:copyId/confirm", async request => { const item = await task(request); const id = String((request.params as Row).copyId); const copy = await database.query<Row>("SELECT * FROM content_task_copies WHERE id=$1 AND task_id=$2", [id,item.id]); if (!copy.rowCount || copy.rows[0].status !== "draft") throw new WorkflowError("Draft copy not found",409); const findings = await review.review(String(item.id),id,`${copy.rows[0].title} ${copy.rows[0].body}`,Number(item.commercial_level) as 0|1|2|3); if (findings.some(x => x.severity === "block" || x.severity === "high")) throw new WorkflowError("Copy has blocking review findings",422,findings); const client=await database.connect(); try{await client.query("BEGIN"); const locked=await client.query<Row>("SELECT confirmed_copy_id FROM content_tasks WHERE id=$1 FOR UPDATE",[item.id]); if(!locked.rowCount||locked.rows[0].confirmed_copy_id)throw new WorkflowError("A copy is already confirmed",409); const result=await client.query<Row>("UPDATE content_task_copies SET status='confirmed',confirmed_at=CURRENT_TIMESTAMP WHERE id=$1 AND task_id=$2 AND status='draft' RETURNING *",[id,item.id]); if(!result.rowCount)throw new WorkflowError("Draft copy not found",409); const pointer=await client.query("UPDATE content_tasks SET status='copy_confirmed',confirmed_copy_id=$2 WHERE id=$1 AND confirmed_copy_id IS NULL",[item.id,id]); if(!pointer.rowCount)throw new WorkflowError("A copy is already confirmed",409); await client.query("COMMIT"); return copyJson(result.rows[0]);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();} });
  app.post("/v1/stores/:storeId/content-tasks/:id/shots/generate", async (request, reply) => { const item=await task(request); if(item.status!=="copy_confirmed"||!item.confirmed_copy_id) throw new WorkflowError("A confirmed copy is required before shots",409); const copy=(await database.query<Row>("SELECT * FROM content_task_copies WHERE id=$1",[item.confirmed_copy_id])).rows[0]; const output=await generator.generateStructured({requestId:`${item.id}:${copy.id}`,promptVersion:"content-shots-v1",commercialLevel:Number(item.commercial_level) as 0|1|2|3,input:{...generationInput(item),copy:copyJson(copy)},schema:shotListSchema}); const client=await database.connect();try{await client.query("BEGIN");await client.query("SELECT id FROM content_tasks WHERE id=$1 FOR UPDATE",[item.id]);const old=await client.query<Row>("SELECT * FROM content_task_shot_lists WHERE task_id=$1 AND copy_id=$2",[item.id,item.confirmed_copy_id]);if(old.rowCount){await client.query("COMMIT");return reply.code(201).send(shotsJson(old.rows[0]));}const saved=await client.query<Row>("INSERT INTO content_task_shot_lists(id,task_id,copy_id,shots_json) VALUES($1,$2,$3,$4) RETURNING *",[randomUUID(),item.id,copy.id,JSON.stringify(output.output)]);await client.query("COMMIT");return reply.code(201).send(shotsJson(saved.rows[0]));}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();} });
  app.setErrorHandler((error, _request, reply) => { if(error instanceof ForbiddenError)return reply.code(403).send({error:error.message}); if(error instanceof WorkflowError)return reply.code(error.status).send({error:error.message,...(error.findings?{findings:error.findings}:{})}); return reply.code(500).send({error:"Internal server error"}); });
}
function optional(value:unknown){return typeof value==="string"&&value.trim()?value.trim():null;} function generationInput(item:Row){return {profile:JSON.parse(String(item.profile_snapshot_json)),stage:JSON.parse(String(item.stage_snapshot_json)),templates:JSON.parse(String(item.template_snapshot_json)),inspiration:item.inspiration};} function taskJson(row:Row){const stage=JSON.parse(String(row.stage_snapshot_json));return {id:row.id,profileVersion:Number(row.profile_version),primaryGoal:stage.primary_goal,status:row.status};} function topicJson(row:Row){return {id:row.id,title:row.title,angle:row.angle,productReference:row.product_reference,goalReference:row.goal_reference,commercialLevel:Number(row.commercial_level)};} function copyJson(row:Row){return {id:row.id,title:row.title,body:row.body,strategy:row.strategy,productReference:row.product_reference,goalReference:row.goal_reference,commercialLevel:Number(row.commercial_level),version:Number(row.version),status:row.status};} function shotsJson(row:Row){return {id:row.id,copyId:row.copy_id,status:row.status,shots:JSON.parse(String(row.shots_json))};} function matchesTemplate(row:Row,profile:Row,input:Row){const c=JSON.parse(String(row.constraints_json)) as Row; return c.industryCode===profile.industry_code&&c.categoryCode===profile.category_code&&c.persona===input.persona&&c.contentType===input.contentType&&c.style===input.style&&Number(c.commercialLevel)===Number(input.commercialLevel);}
