import type { FastifyInstance, FastifyRequest } from "fastify";
import type { Database } from "../db.js";
import { RuleRepository, type RuleInput } from "./rule-repository.js";
import { OperatorContentConflictError, OperatorContentValidationError, TemplateRepository, type TemplateInput } from "./template-repository.js";
export function registerOperatorContentRoutes(app:FastifyInstance,database:Database):void { const templates=new TemplateRepository(database),rules=new RuleRepository(database); app.addHook("onRequest",async(req,reply)=>{if(!req.url.startsWith("/v1/operator-content/")||!req.operatorSession)return reply.code(403).send({error:"Forbidden"});}); const admin=(r:FastifyRequest)=>r.operatorSession!.accountId;
 app.post("/v1/operator-content/templates",async(r,reply)=>reply.code(201).send(await templates.createLogicalItem(templateBody(r.body),admin(r))));app.get("/v1/operator-content/templates",async()=>templates.listLogicalItems());app.get("/v1/operator-content/templates/match",async r=>templates.matchPublishedTemplates(strings(r)));app.get("/v1/operator-content/templates/:id/versions/:version",async r=>templates.getVersion(param(r,"id"),numberParam(r,"version")));app.get("/v1/operator-content/templates/:id/versions",async r=>templates.listVersions(param(r,"id")));app.get("/v1/operator-content/templates/:id/history",async r=>({events:await templates.history(param(r,"id"))}));app.put("/v1/operator-content/templates/:id/draft",async r=>templates.saveDraft(param(r,"id"),templateBody(r.body),admin(r)));app.post("/v1/operator-content/templates/:id/versions/:version/publish",async r=>templates.publishDraft(param(r,"id"),numberParam(r,"version"),admin(r)));app.post("/v1/operator-content/templates/:id/versions/:version/disable",async r=>templates.disablePublished(param(r,"id"),numberParam(r,"version"),admin(r)));
 app.post("/v1/operator-content/rules",async(r,reply)=>reply.code(201).send(await rules.createLogicalItem(ruleBody(r.body),admin(r))));app.get("/v1/operator-content/rules",async()=>rules.listLogicalItems());app.get("/v1/operator-content/rules/active",async()=>rules.listPublishedRules());app.post("/v1/operator-content/rules/preview",async r=>{const b=body(r.body);return rules.previewRule(ruleBody(b.rule),typeof b.text==="string"?b.text:"");});app.get("/v1/operator-content/rules/:id/versions/:version",async r=>rules.getVersion(param(r,"id"),numberParam(r,"version")));app.get("/v1/operator-content/rules/:id/versions",async r=>rules.listVersions(param(r,"id")));app.get("/v1/operator-content/rules/:id/history",async r=>({events:await rules.history(param(r,"id"))}));app.put("/v1/operator-content/rules/:id/draft",async r=>rules.saveDraft(param(r,"id"),ruleBody(r.body),admin(r)));app.post("/v1/operator-content/rules/:id/versions/:version/publish",async r=>rules.publishDraft(param(r,"id"),numberParam(r,"version"),admin(r)));app.post("/v1/operator-content/rules/:id/versions/:version/disable",async r=>rules.disablePublished(param(r,"id"),numberParam(r,"version"),admin(r)));
 app.setErrorHandler((e,_r,reply)=>{if(e instanceof OperatorContentValidationError)return reply.code(422).send({error:e.message});if(e instanceof OperatorContentConflictError)return reply.code(409).send({error:e.message});return reply.code(500).send({error:"Internal server error"});}); }
function body(v:unknown):Record<string,unknown>{if(typeof v!=="object"||v===null||Array.isArray(v))throw new OperatorContentValidationError("Request body must be an object");return v as Record<string,unknown>;}function templateBody(v:unknown){return body(v) as unknown as TemplateInput}function ruleBody(v:unknown){return body(v) as unknown as RuleInput}function param(r:FastifyRequest,k:string){const v=(r.params as Record<string,unknown>)[k];if(typeof v!=="string"||!v)throw new OperatorContentValidationError(`Missing ${k}`);return v}function numberParam(r:FastifyRequest,k:string){const n=Number(param(r,k));if(!Number.isInteger(n)||n<1)throw new OperatorContentValidationError(`Invalid ${k}`);return n}function strings(r:FastifyRequest){return Object.fromEntries(Object.entries(r.query as Record<string,unknown>).filter((x):x is [string,string]=>typeof x[1]==="string"));}
