import { randomUUID } from "node:crypto";
import type { Database, Queryable } from "../db.js";
import { OperatorContentConflictError, OperatorContentValidationError, type LifecycleStatus } from "./template-repository.js";
export interface RuleInput { name:string; ruleType:string; patterns:string[]; semanticCategories:string[]; severity:"block"|"high"|"warning"|"notice"; platform:string; scope:string; guidance:string; }
export interface ReviewRule extends RuleInput { id:string; logicalId:string; version:number; status:LifecycleStatus; }
type Row=Record<string,unknown>;
export class RuleRepository {
 constructor(private readonly database:Database){}
 async createLogicalItem(i:RuleInput,a:string):Promise<ReviewRule>{validate(i);const id=randomUUID(),c=await this.database.connect();try{await c.query("BEGIN");await c.query("INSERT INTO operator_content_rule_items(logical_id) VALUES($1)",[id]);const x=await insert(c,id,1,i,a);await audit(c,id,1,"draft_created",a);await c.query("COMMIT");return x;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
 async saveDraft(id:string,i:RuleInput,a:string):Promise<ReviewRule>{validate(i);const c=await this.database.connect();try{await c.query("BEGIN");const r=await c.query<Row>("SELECT * FROM operator_content_rule_versions WHERE logical_id=$1 ORDER BY version DESC FOR UPDATE",[id]);if(!r.rowCount)throw new OperatorContentValidationError("Rule not found");let x:ReviewRule;if(r.rows[0].status==="draft"){const q=await c.query<Row>("UPDATE operator_content_rule_versions SET name=$3,rule_type=$4,patterns_json=$5,semantic_categories_json=$6,severity=$7,platform=$8,scope=$9,guidance=$10 WHERE logical_id=$1 AND version=$2 RETURNING *",[id,r.rows[0].version,i.name.trim(),i.ruleType.trim(),JSON.stringify(i.patterns),JSON.stringify(i.semanticCategories),i.severity,i.platform.trim(),i.scope.trim(),i.guidance.trim()]);x=toRule(q.rows[0]);await audit(c,id,x.version,"draft_saved",a);}else{x=await insert(c,id,Number(r.rows[0].version)+1,i,a);await audit(c,id,x.version,"draft_created",a);}await c.query("COMMIT");return x;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
 async publishDraft(id:string,v:number,a:string){return this.transition(id,v,"draft","published",a)} async disablePublished(id:string,v:number,a:string){return this.transition(id,v,"published","disabled",a)}
 async listLogicalItems(){return (await this.database.query<Row>("SELECT DISTINCT ON (logical_id) * FROM operator_content_rule_versions ORDER BY logical_id,version DESC")).rows.map(toRule)} async listPublishedRules(){const rows=(await this.database.query<Row>("SELECT * FROM operator_content_rule_versions WHERE status='published' ORDER BY logical_id,version DESC")).rows.map(toRule),latest=new Set<string>();return rows.filter(rule=>{if(latest.has(rule.logicalId))return false;latest.add(rule.logicalId);return true;});}
 async getVersion(id:string,v:number){const r=await this.database.query<Row>("SELECT * FROM operator_content_rule_versions WHERE logical_id=$1 AND version=$2",[id,v]);if(!r.rowCount)throw new OperatorContentValidationError("Rule not found");return toRule(r.rows[0])} async listVersions(id:string){return (await this.database.query<Row>("SELECT * FROM operator_content_rule_versions WHERE logical_id=$1 ORDER BY version DESC",[id])).rows.map(toRule)} async history(id:string){return (await this.database.query<Row>("SELECT version,event_type,actor_id,occurred_at FROM operator_content_audit_events WHERE content_kind='rule' AND logical_id=$1 ORDER BY occurred_at",[id])).rows.map(x=>({version:Number(x.version),eventType:String(x.event_type),actorId:String(x.actor_id),occurredAt:String(x.occurred_at)}))}
 previewRule(i:RuleInput,text:string){validate(i);if(typeof text!=="string")throw new OperatorContentValidationError("text is required");return {matches:i.patterns.filter(p=>text.toLowerCase().includes(p.toLowerCase())).map(pattern=>({pattern,guidance:i.guidance}))}}
 private async transition(id:string,v:number,from:LifecycleStatus,to:LifecycleStatus,a:string){const r=await this.database.query<Row>("UPDATE operator_content_rule_versions SET status=$3 WHERE logical_id=$1 AND version=$2 AND status=$4 RETURNING *",[id,v,to,from]);if(!r.rowCount)throw new OperatorContentConflictError("Rule lifecycle transition is invalid");await audit(this.database,id,v,to,a);return toRule(r.rows[0]);}
}
async function insert(db:Queryable,id:string,v:number,i:RuleInput,a:string){const r=await db.query<Row>("INSERT INTO operator_content_rule_versions(id,logical_id,version,name,rule_type,patterns_json,semantic_categories_json,severity,platform,scope,guidance,status,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'draft',$12) RETURNING *",[randomUUID(),id,v,i.name.trim(),i.ruleType.trim(),JSON.stringify(i.patterns),JSON.stringify(i.semanticCategories),i.severity,i.platform.trim(),i.scope.trim(),i.guidance.trim(),a]);return toRule(r.rows[0]);}async function audit(db:Queryable,id:string,v:number,e:string,a:string){await db.query("INSERT INTO operator_content_audit_events(id,content_kind,logical_id,version,event_type,actor_id) VALUES($1,'rule',$2,$3,$4,$5)",[randomUUID(),id,v,e,a]);}
function validate(i:RuleInput){if(!i||!i.name?.trim()||!i.ruleType?.trim()||!i.platform?.trim()||!i.scope?.trim()||!i.guidance?.trim()||!["block","high","warning","notice"].includes(i.severity)||![i.patterns,i.semanticCategories].every(a=>Array.isArray(a)&&a.length&&a.every(v=>typeof v==="string"&&v.trim())))throw new OperatorContentValidationError("name, rule type, patterns, semantic categories, severity, platform, scope, and guidance are required");}function toRule(r:Row):ReviewRule{return{id:String(r.id),logicalId:String(r.logical_id),version:Number(r.version),name:String(r.name),ruleType:String(r.rule_type),patterns:JSON.parse(String(r.patterns_json)),semanticCategories:JSON.parse(String(r.semantic_categories_json)),severity:String(r.severity) as RuleInput["severity"],platform:String(r.platform),scope:String(r.scope),guidance:String(r.guidance),status:String(r.status) as LifecycleStatus};}
