import { randomUUID } from "node:crypto";
import type { Database, Queryable } from "../db.js";
export type LifecycleStatus = "draft" | "published" | "disabled";
export class OperatorContentValidationError extends Error {}
export class OperatorContentConflictError extends Error {}
export interface TemplateInput { name: string; content: Record<string, unknown>; constraints: Record<string, unknown>; fallbackScope: Record<string, unknown>; }
export interface Template extends TemplateInput { id: string; logicalId: string; version: number; status: LifecycleStatus; }
type Row = Record<string, unknown>;
export class TemplateRepository {
  constructor(private readonly database: Database) {}
  async createLogicalItem(input: TemplateInput, actor: string): Promise<Template> { validateTemplate(input); const id=randomUUID(); const client=await this.database.connect(); try { await client.query("BEGIN"); await client.query("INSERT INTO operator_content_template_items(logical_id) VALUES($1)",[id]); const item=await insert(client,id,1,input,actor); await audit(client,"template",id,1,"draft_created",actor); await client.query("COMMIT"); return item; } catch(e) { await client.query("ROLLBACK"); throw e; } finally { client.release(); } }
  async saveDraft(logicalId: string,input: TemplateInput,actor: string): Promise<Template> { validateTemplate(input); const client=await this.database.connect(); try { await client.query("BEGIN"); const rows=await client.query<Row>("SELECT * FROM operator_content_template_versions WHERE logical_id=$1 ORDER BY version DESC FOR UPDATE",[logicalId]); if(!rows.rowCount) throw new OperatorContentValidationError("Template not found"); const latest=rows.rows[0]; let item: Template; if(latest.status === "draft") { const result=await client.query<Row>("UPDATE operator_content_template_versions SET name=$3,content_json=$4,constraints_json=$5,fallback_scope_json=$6 WHERE logical_id=$1 AND version=$2 RETURNING *",[logicalId,latest.version,input.name.trim(),JSON.stringify(input.content),JSON.stringify(input.constraints),JSON.stringify(input.fallbackScope)]); item=toTemplate(result.rows[0]); await audit(client,"template",logicalId,item.version,"draft_saved",actor); } else { item=await insert(client,logicalId,Number(latest.version)+1,input,actor); await audit(client,"template",logicalId,item.version,"draft_created",actor); } await client.query("COMMIT"); return item; } catch(e) { await client.query("ROLLBACK"); throw e; } finally {client.release();} }
  async publishDraft(logicalId:string,version:number,actor:string):Promise<Template>{ return this.transition(logicalId,version,"draft","published",actor); }
  async disablePublished(logicalId:string,version:number,actor:string):Promise<Template>{ return this.transition(logicalId,version,"published","disabled",actor); }
  async listLogicalItems():Promise<Template[]> { return (await this.database.query<Row>("SELECT DISTINCT ON (logical_id) * FROM operator_content_template_versions ORDER BY logical_id,version DESC")).rows.map(toTemplate); }
  async getVersion(id:string,v:number):Promise<Template>{ const r=await this.database.query<Row>("SELECT * FROM operator_content_template_versions WHERE logical_id=$1 AND version=$2",[id,v]); if(!r.rowCount) throw new OperatorContentValidationError("Template not found"); return toTemplate(r.rows[0]); }
  async listVersions(id:string):Promise<Template[]>{ return (await this.database.query<Row>("SELECT * FROM operator_content_template_versions WHERE logical_id=$1 ORDER BY version DESC",[id])).rows.map(toTemplate); }
  async history(id:string):Promise<unknown[]> { return (await this.database.query<Row>("SELECT version,event_type,actor_id,occurred_at FROM operator_content_audit_events WHERE content_kind='template' AND logical_id=$1 ORDER BY occurred_at",[id])).rows.map(x=>({version:Number(x.version),eventType:String(x.event_type),actorId:String(x.actor_id),occurredAt:String(x.occurred_at)})); }
  async matchPublishedTemplates(criteria:Record<string,string>):Promise<Template[]> { const rows=(await this.database.query<Row>("SELECT * FROM operator_content_template_versions WHERE status='published' ORDER BY logical_id,version DESC")).rows.map(toTemplate); const latest=new Set<string>(); return rows.filter(t=>{if(latest.has(t.logicalId))return false;latest.add(t.logicalId);return Object.entries(criteria).every(([k,v])=>String(t.constraints[k]??"")===v);}); }
  private async transition(id:string,v:number,from:LifecycleStatus,to:LifecycleStatus,actor:string):Promise<Template>{ const client=await this.database.connect();try{await client.query("BEGIN");const r=await client.query<Row>(to==="published"?"UPDATE operator_content_template_versions SET status=$3,ever_published_at=now() WHERE logical_id=$1 AND version=$2 AND status=$4 RETURNING *":"UPDATE operator_content_template_versions SET status=$3,disabled_by_actor_id=$5,disabled_at=now() WHERE logical_id=$1 AND version=$2 AND status=$4 RETURNING *",to==="published"?[id,v,to,from]:[id,v,to,from,actor]);if(!r.rowCount)throw new OperatorContentConflictError("Template lifecycle transition is invalid");await audit(client,"template",id,v,to,actor);await client.query("COMMIT");return toTemplate(r.rows[0]);}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();} }
}
async function insert(db:Queryable,id:string,v:number,i:TemplateInput,actor:string):Promise<Template>{ const r=await db.query<Row>("INSERT INTO operator_content_template_versions(id,logical_id,version,name,status,content_json,constraints_json,fallback_scope_json,actor_id) VALUES($1,$2,$3,$4,'draft',$5,$6,$7,$8) RETURNING *",[randomUUID(),id,v,i.name.trim(),JSON.stringify(i.content),JSON.stringify(i.constraints),JSON.stringify(i.fallbackScope),actor]); return toTemplate(r.rows[0]); }
async function audit(db:Queryable,k:string,id:string,v:number,e:string,a:string){await db.query("INSERT INTO operator_content_audit_events(id,content_kind,logical_id,version,event_type,actor_id) VALUES($1,$2,$3,$4,$5,$6)",[randomUUID(),k,id,v,e,a]);}
function validateTemplate(i:TemplateInput){if(!i||!i.name?.trim()||![i.content,i.constraints,i.fallbackScope].every(record))throw new OperatorContentValidationError("name, content, constraints, and fallbackScope are required"); for(const k of ["hook","story","value","productAppearance","cta","shotRhythm","captionVoiceRequirements"])if(typeof i.content[k]!=="string"||!String(i.content[k]).trim())throw new OperatorContentValidationError(`content.${k} is required`); if(!stringList(i.content.prohibitedExpressions))throw new OperatorContentValidationError("content.prohibitedExpressions is required"); for(const k of ["industryCode","categoryCode","persona","contentType","style","riskLevel"])if(typeof i.constraints[k]!=="string"||!String(i.constraints[k]).trim())throw new OperatorContentValidationError(`constraints.${k} is required`); if(!Number.isInteger(i.constraints.commercialLevel)||Number(i.constraints.commercialLevel)<0||Number(i.constraints.commercialLevel)>3)throw new OperatorContentValidationError("constraints.commercialLevel is invalid");if(!stringList(i.constraints.priceDiscountEffectRestrictions))throw new OperatorContentValidationError("constraints.priceDiscountEffectRestrictions is required");for(const k of ["allowCategoryFallback","allowIndustryFallback"])if(typeof i.fallbackScope[k]!=="boolean")throw new OperatorContentValidationError(`fallbackScope.${k} is required`);}
function record(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v);}
function stringList(v:unknown):v is string[]{return Array.isArray(v)&&v.length>0&&v.every(x=>typeof x==="string"&&x.trim());}
function toTemplate(r:Row):Template{return{id:String(r.id),logicalId:String(r.logical_id),version:Number(r.version),name:String(r.name),status:String(r.status) as LifecycleStatus,content:JSON.parse(String(r.content_json)),constraints:JSON.parse(String(r.constraints_json)),fallbackScope:JSON.parse(String(r.fallback_scope_json))};}
