import { randomUUID } from "node:crypto";
import type { Database, Queryable } from "../db.js";
import { sanitizeInternalAuditMetadata } from "../admin/rbac.js";

export type PriceStatus = "draft" | "published" | "retired";
export interface PriceVersion { id: string; provider: string; model: string; inputCnyPerMillionTokens: number; outputCnyPerMillionTokens: number; effectiveFrom: string; effectiveTo: string | null; status: PriceStatus; currency: "CNY"; }
export interface UsageAggregate { date: string; provider: string; model: string; inputTokens: number; outputTokens: number; totalTokens: number; inputCostCny: number; outputCostCny: number; totalCostCny: number; callCount: number; successCount: number; }
export class ModelPricingRepository {
  constructor(private readonly database: Database) {}
  async create(input: Omit<PriceVersion, "id" | "effectiveTo" | "status" | "currency">): Promise<PriceVersion> { const id = randomUUID(); const r = await this.database.query<Row>("INSERT INTO model_token_price_versions (id,provider,model,input_cny_per_million_tokens,output_cny_per_million_tokens,effective_from,status) VALUES ($1,$2,$3,$4,$5,$6,'draft') RETURNING *", [id,input.provider,input.model,input.inputCnyPerMillionTokens,input.outputCnyPerMillionTokens,input.effectiveFrom]); return version(r.rows[0]); }
  async list(): Promise<PriceVersion[]> { const r = await this.database.query<Row>("SELECT * FROM model_token_price_versions ORDER BY created_at DESC"); return r.rows.map(version); }
  async updateDraft(id: string, input: Pick<PriceVersion,"provider"|"model"|"inputCnyPerMillionTokens"|"outputCnyPerMillionTokens"|"effectiveFrom">): Promise<PriceVersion | undefined> { const r = await this.database.query<Row>("UPDATE model_token_price_versions SET provider=$2,model=$3,input_cny_per_million_tokens=$4,output_cny_per_million_tokens=$5,effective_from=$6 WHERE id=$1 AND status='draft' RETURNING *", [id,input.provider,input.model,input.inputCnyPerMillionTokens,input.outputCnyPerMillionTokens,input.effectiveFrom]); return r.rowCount ? version(r.rows[0]) : undefined; }
  async publish(id: string): Promise<PriceVersion | undefined> { const r = await this.database.query<Row>("UPDATE model_token_price_versions SET status='published' WHERE id=$1 AND status='draft' RETURNING *", [id]); return r.rowCount ? version(r.rows[0]) : undefined; }
  async retire(id: string, effectiveTo: string): Promise<PriceVersion | undefined> { const r = await this.database.query<Row>("UPDATE model_token_price_versions SET status='retired',effective_to=$2 WHERE id=$1 AND status='published' RETURNING *", [id,effectiveTo]); return r.rowCount ? version(r.rows[0]) : undefined; }
  async createAndAudit(actorId: string, input: Omit<PriceVersion, "id" | "effectiveTo" | "status" | "currency">) { return this.atomicAudit(actorId, "model_pricing.created", db => create(db, input)); }
  async updateDraftAndAudit(actorId: string, id: string, input: Pick<PriceVersion,"provider"|"model"|"inputCnyPerMillionTokens"|"outputCnyPerMillionTokens"|"effectiveFrom">) { return this.atomicAudit(actorId, "model_pricing.updated", db => updateDraft(db, id, input)); }
  async publishAndAudit(actorId: string, id: string) { return this.atomicAudit(actorId, "model_pricing.published", db => publish(db, id)); }
  async retireAndAudit(actorId: string, id: string, effectiveTo: string) { return this.atomicAudit(actorId, "model_pricing.retired", db => retire(db, id, effectiveTo)); }
  async usage(from: string, toExclusive: string): Promise<UsageAggregate[]> { const r = await this.database.query<Row>("SELECT created_at,provider,model,usage_json,input_cost,output_cost,total_cost,status FROM content_task_generation_runs WHERE created_at >= $1 AND created_at < $2", [from,toExclusive]); const items = new Map<string, UsageAggregate>(); for (const row of r.rows) { const date = new Date(String(row.created_at)).toISOString().slice(0,10); const provider=String(row.provider); const model=String(row.model); const key=`${date}\u0000${provider}\u0000${model}`; const usage=parseUsage(row.usage_json); const current=items.get(key) ?? {date,provider,model,inputTokens:0,outputTokens:0,totalTokens:0,inputCostCny:0,outputCostCny:0,totalCostCny:0,callCount:0,successCount:0}; current.inputTokens+=usage.inputTokens; current.outputTokens+=usage.outputTokens; current.totalTokens+=usage.totalTokens; current.inputCostCny+=Number(row.input_cost ?? 0); current.outputCostCny+=Number(row.output_cost ?? 0); current.totalCostCny+=Number(row.total_cost ?? 0); current.callCount+=1; current.successCount+=row.status === "succeeded" ? 1 : 0; items.set(key,current); } return [...items.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.provider.localeCompare(b.provider)||a.model.localeCompare(b.model)); }
  private async atomicAudit(actorId: string, action: string, mutation: (database: Queryable) => Promise<PriceVersion | undefined>) { const client = await this.database.connect(); try { await client.query("BEGIN"); const item = await mutation(client); if (!item) { await client.query("COMMIT"); return undefined; } await client.query("INSERT INTO internal_audit_events(id,actor_account_id,action_code,target_type,target_id,succeeded,metadata_json) VALUES($1,$2,$3,'model_pricing_version',$4,true,$5)", [randomUUID(),actorId,action,item.id,JSON.stringify(sanitizeInternalAuditMetadata({priceVersionId:item.id,provider:item.provider,model:item.model,priceStatus:item.status,effectiveFrom:item.effectiveFrom,effectiveTo:item.effectiveTo}))]); await client.query("COMMIT"); return item; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
}
type Row = Record<string, unknown>;
async function create(database: Queryable, input: Omit<PriceVersion, "id" | "effectiveTo" | "status" | "currency">): Promise<PriceVersion> { const id = randomUUID(); const r = await database.query<Row>("INSERT INTO model_token_price_versions (id,provider,model,input_cny_per_million_tokens,output_cny_per_million_tokens,effective_from,status) VALUES ($1,$2,$3,$4,$5,$6,'draft') RETURNING *", [id,input.provider,input.model,input.inputCnyPerMillionTokens,input.outputCnyPerMillionTokens,input.effectiveFrom]); return version(r.rows[0]); }
async function updateDraft(database: Queryable, id: string, input: Pick<PriceVersion,"provider"|"model"|"inputCnyPerMillionTokens"|"outputCnyPerMillionTokens"|"effectiveFrom">) { const r = await database.query<Row>("UPDATE model_token_price_versions SET provider=$2,model=$3,input_cny_per_million_tokens=$4,output_cny_per_million_tokens=$5,effective_from=$6 WHERE id=$1 AND status='draft' RETURNING *", [id,input.provider,input.model,input.inputCnyPerMillionTokens,input.outputCnyPerMillionTokens,input.effectiveFrom]); return r.rowCount ? version(r.rows[0]) : undefined; }
async function publish(database: Queryable, id: string) { const r = await database.query<Row>("UPDATE model_token_price_versions SET status='published' WHERE id=$1 AND status='draft' RETURNING *", [id]); return r.rowCount ? version(r.rows[0]) : undefined; }
async function retire(database: Queryable, id: string, effectiveTo: string) { const r = await database.query<Row>("UPDATE model_token_price_versions SET status='retired',effective_to=$2 WHERE id=$1 AND status='published' RETURNING *", [id,effectiveTo]); return r.rowCount ? version(r.rows[0]) : undefined; }
function version(row: Row): PriceVersion { return { id:String(row.id),provider:String(row.provider),model:String(row.model),inputCnyPerMillionTokens:Number(row.input_cny_per_million_tokens),outputCnyPerMillionTokens:Number(row.output_cny_per_million_tokens),effectiveFrom:new Date(String(row.effective_from)).toISOString(),effectiveTo:row.effective_to == null ? null : new Date(String(row.effective_to)).toISOString(),status:row.status as PriceStatus,currency:"CNY" }; }
function parseUsage(value: unknown) { try { const parsed=JSON.parse(String(value ?? "{}")) as Record<string,unknown>; return { inputTokens:Number(parsed.inputTokens ?? 0), outputTokens:Number(parsed.outputTokens ?? 0), totalTokens:Number(parsed.totalTokens ?? 0) }; } catch { return {inputTokens:0,outputTokens:0,totalTokens:0}; } }
