import type { FastifyInstance, FastifyRequest } from "fastify";
import type { AuthService } from "../auth/service.js";
import { AuthenticationError } from "../auth/tokens.js";
import type { Database } from "../db.js";
import { ModelPricingRepository } from "./repository.js";
export async function registerModelPricingRoutes(app: FastifyInstance, options: { auth: AuthService; database: Database }): Promise<void> { const repository = new ModelPricingRepository(options.database); const requireRole = async (request: FastifyRequest) => { const token = bearer(request); if (!token) throw new AuthenticationError("Authentication required"); return options.auth.requireServiceOperatorRole(token,"model_pricing_operator"); };
  app.get("/v1/provider-model-pricing/versions", async (request, reply) => guarded(request,reply, async () => ({ items: await repository.list() })));
  app.post("/v1/provider-model-pricing/versions", async (request,reply) => guarded(request,reply, async () => { marker(request); await requireRole(request); return reply.code(201).send(await repository.create(parsePrice(request.body))); }));
  app.put("/v1/provider-model-pricing/versions/:id", async (request,reply) => guarded(request,reply, async () => { marker(request); await requireRole(request); const result=await repository.updateDraft(id(request.params),parsePrice(request.body)); return result ?? reply.code(404).send({error:"Price draft is not available"}); }));
  app.post("/v1/provider-model-pricing/versions/:id/publish", async (request,reply) => guarded(request,reply, async () => { marker(request); await requireRole(request); const result=await repository.publish(id(request.params)); return result ?? reply.code(409).send({error:"Price draft cannot be published"}); }));
  app.post("/v1/provider-model-pricing/versions/:id/retire", async (request,reply) => guarded(request,reply, async () => { marker(request); await requireRole(request); const date=string((request.body as Record<string,unknown>)?.effectiveTo,"effectiveTo"); const result=await repository.retire(id(request.params),date); return result ?? reply.code(409).send({error:"Published price cannot be retired"}); }));
  app.get("/v1/provider-model-pricing/usage", async (request,reply) => guarded(request,reply, async () => { await requireRole(request); const query=request.query as Record<string,unknown>; const from=date(query.from,"from"); const to=date(query.to,"to"); const end=new Date(to); end.setUTCDate(end.getUTCDate()+1); return {items:await repository.usage(from,end.toISOString())}; })); }
async function guarded(request: FastifyRequest, reply: any, operation: () => Promise<unknown>) { try { return await operation(); } catch (error) { if (error instanceof AuthenticationError) return reply.code(401).send({error:"Authentication required"}); if (error instanceof Error && (error.message.includes("Service role") || error.message.includes("Provider console"))) return reply.code(403).send({error:"Model pricing access is required"}); if (error instanceof Error && error.message.startsWith("Invalid")) return reply.code(422).send({error:error.message}); throw error; } }
function bearer(request: FastifyRequest) { return /^Bearer ([A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)$/.exec(request.headers.authorization ?? "")?.[1]; } function marker(request: FastifyRequest) { if(request.headers["x-provider-console-request"]!=="1") throw new Error("Provider console request is required"); } function id(params: unknown) { return string((params as Record<string,unknown>).id,"id"); } function string(value:unknown,name:string) { if(typeof value!=="string"||!value.trim()||value.length>128) throw new Error(`Invalid ${name}`); return value.trim(); } function date(value:unknown,name:string) { const valueText=string(value,name); if(Number.isNaN(Date.parse(valueText))) throw new Error(`Invalid ${name}`); return valueText; } function number(value:unknown,name:string) { if(typeof value!=="number"||!Number.isFinite(value)||value<0) throw new Error(`Invalid ${name}`); return value; } function parsePrice(body:unknown) { const item=body as Record<string,unknown>; return {provider:string(item?.provider,"provider"),model:string(item?.model,"model"),inputCnyPerMillionTokens:number(item?.inputCnyPerMillionTokens,"inputCnyPerMillionTokens"),outputCnyPerMillionTokens:number(item?.outputCnyPerMillionTokens,"outputCnyPerMillionTokens"),effectiveFrom:date(item?.effectiveFrom,"effectiveFrom")}; }
